// The 15th Grade: life's big calls, advanced. Demo course for review:
// full structure, three units carry complete lessons.

import type { Course } from "./lms";

export const COURSE_15: Course = {
  slug: "the-15th-grade",
  title: "The 15th Grade",
  kicker: "Course Three",
  tone: "coral",
  status: "preview",
  headline: "The big calls: career, home, and the people you build a life with.",
  description:
    "Frameworks for the decisions that shape your decade: quitting, moving, buying, marrying, caring for parents. 12 units, no easy answers pretended, real ones worked through.",
  parts: [
    {
      id: "work",
      name: "Work Calls",
      tone: "acc",
      tagline: "Your career is a series of decisions, not a ladder.",
      action: "Apply this chapter's framework to your actual job situation on paper.",
      units: [
        { slug: "quit-or-stay", title: "Quit or Stay", blurb: "The four signals that say go, the two that say wait, and the exit done right.", live: true },
        { slug: "career-pivots", title: "Career Pivots", blurb: "Changing lanes without starting from zero: what transfers and what doesn't.", live: false },
        { slug: "grad-school-math", title: "Grad School Math", blurb: "When the degree pays for itself, and when it's an expensive pause button.", live: false },
        { slug: "starting-something", title: "Starting Something", blurb: "Side project to real business: the checkpoints that tell you to keep going.", live: false },
      ],
    },
    {
      id: "home",
      name: "Home Calls",
      tone: "vio",
      tagline: "Where you live decides more than you think.",
      action: "Run this chapter's numbers on your real city, rent, and timeline.",
      units: [
        { slug: "rent-vs-buy", title: "Rent vs Buy", blurb: "The five-year rule, the hidden costs, and why renting is often the smart move.", live: true },
        { slug: "moving-math", title: "Moving Math", blurb: "New city, new country, new cost of living: the full comparison, not just salary.", live: false },
        { slug: "living-with-parents", title: "Living With Parents", blurb: "Moving back home with a plan: saving aggressively without losing momentum.", live: false },
        { slug: "first-home-playbook", title: "First Home Playbook", blurb: "Down payments, mortgages, inspections: the process from search to keys.", live: false },
      ],
    },
    {
      id: "people",
      name: "People Calls",
      tone: "coral",
      tagline: "The biggest financial decisions are relationship decisions.",
      action: "Have (or schedule) one conversation this chapter says you're overdue for.",
      units: [
        { slug: "partner-money-talks", title: "Partner Money Talks", blurb: "The five conversations to have before you combine anything.", live: true },
        { slug: "wedding-math", title: "Wedding Math", blurb: "Celebrating big without starting married life in debt, and handling family expectations.", live: false },
        { slug: "the-kids-question", title: "The Kids Question", blurb: "The real costs, the real timelines, and deciding on purpose instead of by default.", live: false },
        { slug: "aging-parents", title: "Aging Parents", blurb: "Supporting the people who raised you: money, care, and boundaries that keep love intact.", live: false },
      ],
    },
  ],
  lessons: {
    "quit-or-stay": {
      hook: "\"Should I quit?\" asks your mood. \"What would have to change for staying to be worth it?\" asks the facts.",
      blocks: [
        { kind: "p", text: "It is 9:40 on a Sunday night and Sam is looking at a resignation email he has never sent. The draft is five months old. It says \"Hi Priya,\" and nothing else. On bad Fridays he composes the rest of it in his head, whole paragraphs, some of them excellent. On decent Tuesdays he decides he was being dramatic. He has told two friends he is quitting and one that he is staying, and he believed himself all three times." },
        { kind: "p", text: "Sam is not deciding. He is orbiting. And he is orbiting because all the advice he gets comes in two slogans that point opposite ways while sharing one flaw: both make the decision before anyone has looked at the job." },
        { kind: "h", text: "Two Slogans, Both Wrong" },
        { kind: "p", text: "The first slogan is winners never quit. It sounds like grit and is really a rule that staying is always right, which cannot be true: some jobs are dead ends and some rooms are on fire. The second is life is too short. It sounds like freedom and is really a rule that leaving is always right, which cannot be true either: everything worth having gets boring and hard somewhere in the middle, and a person who leaves at every rough patch ends up with a pile of beginnings." },
        { kind: "p", text: "A slogan is a decision somebody else made in advance, handed to you with the reasoning removed. What Sam needs, and what this unit is, is a method: a way to look at one particular job in one particular year and come out with an answer he can defend in either direction. An honest method has to be able to come out either way. If it can only ever say one thing, it is a slogan with extra steps." },
        { kind: "h", text: "The Year Already Spent" },
        { kind: "p", text: "Say you have put three years into this job: learning their systems, banking goodwill, becoming the person who knows where everything is. Walking away feels like setting all of that on fire. Here is the accounting truth: those years are spent. You spent them whichever way you now choose. Staying does not refund them and leaving does not erase them; they already happened, to the same degree, in both futures. Money people call this sunk cost, and the rule for sunk costs is that they belong in neither column of the decision." },
        { kind: "callout", title: "The rule", text: "The years already spent are gone whichever way you choose, so they get no vote. The only thing still for sale is the next year. The whole decision is what the next year buys here, against what it buys somewhere else." },
        { kind: "p", text: "Then notice which way the scale tilts on its own. Quitting has a visible cost: a resignation meeting you can dread by name, an income gap you can count in dollars, an awkward phone call home. Staying has an invisible one: the raise that never arrives, the skills that never develop, the other job you never take. Nobody schedules a meeting to show you the year that did not happen. So the visible cost feels enormous, the invisible one feels like nothing, and people stay years past the point where staying made sense. Not because they weighed it and chose, but because only one side ever showed up on a screen." },
        { kind: "bigfact", stat: "1 year", caption: "The only thing actually on the table. The years behind you are spent in both futures. The decision is what the next one buys." },
        { kind: "h", text: "Bad Season or Bad Fit" },
        { kind: "p", text: "The next distinction is the one most people get wrong, in both directions. A bad season is a job that is temporarily on fire: a layoff round, a brutal launch, a new boss still marking territory. It has a start date you can name and a plausible end you can describe. A bad fit is different: nothing went wrong. The job is running exactly as designed, and the design is the problem: the work itself, the pace itself, the ceiling itself. A season passes. A fit does not, because there is nothing to pass." },
        { kind: "split", title: "Season or Fit", leftLabel: "Bad season", rightLabel: "Bad fit", rows: [
          { left: "Started on a date you can name: the layoffs, the launch, the new boss", right: "No start date; it has felt this way whenever you checked" },
          { left: "You can name the change that would end it", right: "You cannot describe a fix that keeps the job the same job" },
          { left: "On a rare calm day, you still like the work", right: "The calm days give you the clearest view of the problem" },
          { left: "Your best month here was recent", right: "Your best month here was your first" },
          { left: "Six more months could plausibly be different", right: "Six more months buys the same year again" },
        ] },
        { kind: "p", text: "Both misreads are expensive. Read a season as a fit and you quit a good job at its worst moment, usually right before it recovers, and pay moving costs to escape weather. Read a fit as a season and you wait out something that is not weather at all, twelve months at a time, always about to get better. The split above is the check. Be suspicious in both directions: on a terrible week everything looks like a fit, on a good one everything looks like a season." },
        { kind: "divider" },
        { kind: "h", text: "The Test With a Date" },
        { kind: "p", text: "Here is the working part of the method. Do not ask \"should I quit?\" That question gets answered by whatever mood you are in, which is why Sam has answered it forty times and kept none of the answers. Ask instead: what would have to change for the next year here to be worth having? Write the answers down, specific enough to check: a number, a schedule, a kind of work. Three lines is plenty. If you cannot write a single believable line, notice that, because you just answered the question." },
        { kind: "p", text: "Then interrogate each line with two questions. Is that change actually available? And who controls it? The second question is the one people skip, and it is the whole test. \"My manager stops undermining me in meetings\" is controlled by your manager's character. A change you can get by asking is an option. A change that requires another person to become a different person is a hope. If every line on your list depends on somebody else changing, that is not pessimism. That is a fact about your options, and you are allowed to act on facts." },
        { kind: "table", title: "The Stay List", head: ["What has to change", "Who controls it", "Actually available?"], rows: [
          ["A raise to $55,000", "Manager and their budget", "Asked 05-02; silence so far"],
          ["Off the 6 am rotation", "The scheduler", "Yes; fixed in a week"],
          ["Real projects, not tickets", "Manager", "Askable; not yet asked"],
          ["A manager who prepares", "Nobody you can ask", "A hope, not an option"],
        ], caption: "Anything that needs another person to become a different person goes in the hope column, and hopes get no vote." },
        { kind: "p", text: "Then the part almost nobody does: put a date on it. An open-ended test never concludes; it just becomes the new way you live. Sixty to ninety days is long enough for real answers to arrive and short enough that you cannot drift." },
        { kind: "steps", title: "Run the Decision", steps: [
          { label: "Write the terms", text: "Three lines: what would make the next year here worth having. Specific enough that a stranger could check them." },
          { label: "Ask on the record", text: "Every line you control by asking, ask for in writing, with a number wherever a number applies." },
          { label: "Set the date", text: "Pick a day 60 to 90 days out and put it in your calendar. The decision happens then, not on your worst Friday." },
          { label: "Collect the answers", text: "Save the replies. Silence is a reply. \"Next cycle\" for the second time is a reply too." },
          { label: "Decide on the date", text: "Compare the list to what happened. Act on the record you collected, not the week you happened to have." },
        ] },
        { kind: "h", text: "The Identity Bill" },
        { kind: "p", text: "Now the real reason people stay, which is rarely the paycheck. If you have been at a thing long enough to be asking this question, the thing has probably become your answer to \"what do you do?\" Leaving costs a self-description along with an income, and the self-description is often the harder loss, because there is no severance for it. People will say they are staying for the insurance when they are staying for the sentence they get to say at parties. No shame in that. But you have to name it, because a cost you refuse to name gets to vote in secret, and it always votes stay." },
        { kind: "quote", text: "I had eight months of savings. The money was never the problem. The problem was the pause after somebody asked what I did.", who: "Renata, 15th Grade" },
        { kind: "p", text: "One more honesty check before the method clears anyone to leave. Look at the last few things you quit and mark the stage you left each one at. Everything worth doing has a stretch where it has stopped being new and is not yet good: competent enough to be bored, junior enough to be ignored, often between month six and year two. Quitting there once is information. Quitting there every time is a pattern wearing a series of costumes." },
        { kind: "callout", title: "Watch out", text: "A true misfit feels worse as you get better at it, because mastery just gives you a clearer view of the problem. The flat middle feels better with every month you push through it. One more tell: look at the people two rungs above you. If you would take their job, you are in a dip. If their life reads like a warning label, that is the fit talking." },
        { kind: "h", text: "Change the Terms First" },
        { kind: "p", text: "Between staying as things are and leaving, there is a middle band of moves most people never try, because by the time they are thinking this hard they have already privately resigned. Different scope. A different team under the same roof. Four days instead of five. Employers grant these more often than anyone expects, mostly to people who ask before the resignation letter, while the asking still reads as commitment instead of a ransom note. Asking is cheap: the worst case is a no, and a no is exactly the kind of fact your stay list exists to collect." },
        { kind: "scale", title: "More Than Two Doors", left: "Stay as is", right: "Gone entirely", marks: [
          { at: 18, label: "Same job, new terms", tone: "good" },
          { at: 42, label: "New team, same employer", tone: "good" },
          { at: 70, label: "Same work, new employer" },
          { at: 92, label: "New line of work" },
        ], caption: "The two ends get all the conversation. The middle gets most of the results." },
        { kind: "example", title: "Worked example: Dana's ninety days", text: "Dana, 24, is a support lead at a freight brokerage making $49,000, and by August the quitting fantasy has stopped being fun. She runs the test. Her list: a raise to $55,000, off the 6 am rotation, and real ops work instead of tickets. On the first ask, she blinks. She softens the whole thing to \"I'd love more growth eventually,\" her manager says \"love that energy,\" and she walks out with nothing and nearly logs it as an ask. It was not one. A week later she recovers: one email, three lines, real numbers, answers requested within two months. She circles 11-06 on her calendar and waits. The rotation is fixed in six days; the scheduler simply had not known she wanted off it. The raise comes back \"next cycle,\" the second \"next cycle\" this year. The ops path turns out to run through a director who has filled the last three openings from outside. On 11-06 she reads the record: one term met, one refused twice, one not actually available. She interviews while employed, takes an ops role at another brokerage for $56,000, gives two weeks, writes the handover doc, and trains her replacement on the queue herself. Eight months later her old manager, at a new company by then, is the reference that gets her the job after that." },
        { kind: "h", text: "Leaving Well" },
        { kind: "p", text: "If the date arrives and the record says go, then go like a professional, because every industry is a small town wearing a big city's name. The manager you leave today is a reference in two years and a client in five. The coworker who watched your last two weeks at full effort will repeat that story, and so will the one who watched you coast. None of this requires pretending you were happy. It requires finishing." },
        { kind: "list", title: "The exit, done properly", items: [
          "Give real notice, and give it to your manager directly before anyone else in the building hears it.",
          "Write the handover document nobody asked for: the state of every open thing, where it lives, who is waiting on what.",
          "Thank two or three people specifically, in writing they can keep, for things you actually mean.",
          "Say less in the exit interview than you rehearsed; the truth delivered on the way out changes nothing and follows you.",
          "Work the last two weeks like the reference depends on it, because that is exactly what the reference is.",
        ] },
        { kind: "p", text: "None of this makes the call painless, and it is not supposed to. What it does is smaller and better: it takes the spent years off the scale, prices the next one honestly, turns hopes into questions somebody actually answered, and gives the whole thing a date. Sam's draft still says \"Hi Priya,\" and either sentence he writes next is fine. On the record, staying is a decision and leaving is a decision. Seven months of orbit was the only wrong answer." },
      ],
      takeaways: [
        "\"Should I quit?\" gets answered by your mood; \"what would have to change for the next year here to be worth having?\" gets answered by facts you can collect.",
        "The years you already spent are gone whichever way you choose, so they belong in neither column; the only thing still for sale is the next year.",
        "Quitting has a visible cost and staying has an invisible one, which is why people stay years past the point it made sense.",
        "A bad season has a start date, a nameable cause, and a plausible end; a bad fit is the job working exactly as designed.",
        "Every line on your stay list gets two questions: is the change actually available, and who controls it. A change that needs another person to become different is a hope, and hopes get no vote.",
        "Put a date on the decision, 60 to 90 days out, and on that date read the record you collected instead of the week you happened to have.",
        "When the job has been your answer to \"what do you do,\" leaving costs a self-description along with an income; name that cost or it votes in secret.",
        "Quitting the same kind of thing at the same stage over and over is a pattern to break, not a series of decisions; a true misfit feels worse as you improve, and the flat middle feels better.",
        "Changing the terms, meaning scope, team, or schedule, is usually available and rarely requested; ask before you resign, and if you do leave, leave the bridge standing.",
      ],
      theLesson: "Leave the spent years out of it, price what the next year buys, ask on the record what would have to change and who controls it, then decide on a date and, whichever door you take, take it well.",
      quiz: [
        {
          q: "You have three years in at a job you now dread. Which way do those three years count in the decision?",
          options: [
            "Toward staying: walking away now would waste the investment",
            "Toward leaving: three years is more than any bad job deserves",
            "Nothing in either column: they are spent whichever way you choose",
            "Toward staying, but only if a promotion is genuinely close",
          ],
          answer: 2,
          explain: "The years are sunk cost: spent in both futures, so they get no vote. \"Waste the investment\" is the trap, because you cannot waste what is already gone; you can only spend the next year honoring it. Counting them \"toward leaving\" makes the same mistake in reverse. The only live question is what the next year buys.",
        },
        {
          q: "Why do people so often stay years past the point a job made sense?",
          options: [
            "Quitting's cost is visible up front; staying's cost never shows up anywhere",
            "Most people genuinely cannot afford even a short unpaid gap between jobs",
            "Staying is usually the mathematically better option, and people sense that",
            "Managers quietly work to retain people who are privately close to leaving",
          ],
          answer: 0,
          explain: "You can dread the resignation meeting by name and count the income gap in dollars, but nobody shows you the raise that never came or the skills that never grew, so the invisible side weighs nothing. \"Cannot afford a gap\" fails because you can interview while employed and leave with no gap at all. The scale is tilted, and it tilts toward the chair you are already in.",
        },
        {
          q: "Your job turned miserable the month a new director arrived, and your best stretch here was this spring. The evidence points to...",
          options: [
            "A bad fit: once a job turns on you, it does not turn back",
            "A bad fit: blaming one arrival usually hides a deeper problem",
            "A bad season, which means waiting quietly is the whole plan",
            "A bad season: it has a start date and a recent good stretch",
          ],
          answer: 3,
          explain: "A nameable start date and a recent good month are the classic season marks: something specific changed, and the job was working before it did. \"Does not turn back\" is a slogan, not evidence; directors move and pressure passes. But a season does not mean \"waiting quietly\": you can still ask, change terms, and set a date for how long the season gets.",
        },
        {
          q: "One line of your stay list reads \"my manager stops undermining me in meetings.\" The method calls that line...",
          options: [
            "Fair and actionable, as long as you raise it with your manager directly",
            "A hope, because it requires another person to become a different person",
            "A reason to escalate straight to your manager's manager this week",
            "Proof the job is a bad fit for you rather than a bad season",
          ],
          answer: 1,
          explain: "You can ask for projects, schedules, and money, because those are decisions somebody can grant. A change in somebody's character is not a decision anyone can grant, so a stay built on it is built on a hope. \"Raise it with your manager\" sounds reasonable, but even a well-received conversation leaves the change in their hands, not yours. That is a fact about your options, and facts are what the list is for.",
        },
        {
          q: "You realize you have left three pursuits in a row somewhere around month eight. What separates a true misfit from the flat middle?",
          options: [
            "Count the ratio: any month with more bad days than good means misfit",
            "A misfit shows up early, while the flat middle only appears after years",
            "A misfit feels worse as you get better; the flat middle improves as you push",
            "There is no reliable difference, which is why the pattern keeps repeating",
          ],
          answer: 2,
          explain: "Getting better at a bad fit just gives you a clearer view of the problem, so mastery makes it worse. The flat middle rewards pushing: every month, competent turns a little more into trusted. \"More bad days than good\" fails because the flat middle produces exactly that ratio for a while in things that turn out great. Three exits at the same mile marker is a pattern, and the fix starts with knowing which stretch you are standing in.",
        },
        {
          q: "You mostly want out because of the 6 am shift and the ticket queue. Before resigning, the method says...",
          options: [
            "Ask to change the terms: schedule and scope are often granted on request",
            "Resign first, because asking for changes marks you as a flight risk",
            "Hold everything until the annual review, where terms actually change",
            "Trust the feeling and start interviewing quietly that same week",
          ],
          answer: 0,
          explain: "If the problem is two specific terms, the cheapest experiment is asking for different terms while the asking still reads as commitment. In Dana's case the schedule was fixed in six days because the scheduler simply did not know. \"Flight risk\" has it backward: a person asking for terms is signaling a wish to stay, and a no costs nothing except exactly the information your stay list needed anyway.",
        },
      ],
      cards: [
        { front: "Sunk cost", back: "The years already spent are gone whichever way you choose, so they belong in neither column. The only question with money still on the table is what the next year buys." },
        { front: "The stay list", back: "The changes that would make the next year worth having, each with two checks: is it actually available, and who controls it." },
        { front: "Hope vs option", back: "A change you can get by asking is an option. A change that requires another person to become a different person is a hope, and hopes get no vote." },
        { front: "Bad season vs bad fit", back: "A season has a start date, a nameable cause, and a plausible end. A fit problem is the job working exactly as designed, so there is nothing to wait out." },
        { front: "The staying asymmetry", back: "Quitting's cost is visible on day one. Staying's cost never appears on any screen, which is why the default is to stay too long." },
        { front: "The identity bill", back: "When the job is your answer to \"what do you do,\" leaving costs a self-description along with an income. Name the cost so it stops voting in secret." },
        { front: "The pattern check", back: "Quitting the same kind of thing at the same stage, over and over, is a pattern rather than a decision. A misfit feels worse as you improve; the flat middle feels better." },
        { front: "Change the terms first", back: "Scope, team, schedule, and pay are all negotiable before the resignation is. Often available, rarely requested, and a no is free information." },
        { front: "Leave well", back: "Real notice, a handover document, specific thank-yous, full effort to the last day. Every industry is a small town; the bridge you leave standing is an asset." },
      ],
      action: "Tonight, write your stay list: the changes that would make the next year worth having, who controls each one, and whether you have actually asked. Then put a decision date 60 to 90 days out in your calendar before you close the notebook.",
    },
    "rent-vs-buy": {
      hook: "\"Rent is throwing money away\" is the most expensive sentence in family group chats. Here is the arithmetic it skips.",
      blocks: [
        { kind: "p", text: "It is a Saturday afternoon in October and you are at your cousin's housewarming, holding a paper plate, while your uncle explains your finances to you. \"Every rent check is a gift to your landlord,\" he says, gesturing at the new granite with a meatball on a toothpick. \"You're paying somebody's mortgage. It just isn't yours.\" Your cousin is 29. You are 24, your lease renews in March, and on the drive home the sentence sits in your chest like a verdict. It is also, as accounting, wrong." },
        { kind: "p", text: "Here is what the sentence gets right: rent is money you never see again. Here is what it hides: so is most of a house payment. Both ways of putting a roof over your head burn money every month, and the honest question was never rent or own as a matter of character. The question is which pile of burned money is smaller, for your numbers, in your city, for as long as you are actually going to stay. Seen that way, it stops being a moral test and becomes arithmetic you can run at a kitchen table in one evening." },
        { kind: "h", text: "Two Piles Of Gone Money" },
        { kind: "p", text: "Call a housing cost unrecoverable if it buys you the month and nothing else. For a renter the accounting is brutally simple: the whole check is unrecoverable, and the whole check is also the entire cost. For an owner the unrecoverable pile hides inside respectable-looking payments: the interest portion of the mortgage, property tax, homeowner's insurance, maintenance, and the transaction fees charged at both ends of ownership. Only the principal portion of a mortgage payment, the slice that actually pays down the loan, is money you keep, because it becomes equity you can get back when you sell. Everything else on the owner's side is as gone as rent." },
        { kind: "split", title: "The Saying Against The Ledger", leftLabel: "What the saying claims", rightLabel: "What the ledger shows", rows: [
          { left: "Rent disappears every month", right: "So do interest, tax, insurance, upkeep" },
          { left: "A house payment builds equity", right: "Only the principal slice does" },
          { left: "Owning ends the landlord's cut", right: "The bank and the county take their own" },
          { left: "Buying is the responsible default", right: "Buying is a bet on staying put" },
          { left: "Renters end up with nothing", right: "Renters keep the down payment invested" },
        ] },
        { kind: "p", text: "Notice what this framing does. It does not tell you renting wins or owning wins, because neither is true as a slogan. It hands you a fair fight: rent on one side, and on the other side everything an owner pays that they never get back. Whichever pile is smaller over your actual timeline is the cheaper roof. That is the entire dispute your uncle thought he settled with a meatball." },
        { kind: "h", text: "Finish The Payment" },
        { kind: "p", text: "The most common mistake in this decision is comparing rent to a mortgage payment and stopping. A lender's quote of $1,700 a month against your $1,700 rent looks like a tie that equity breaks in favor of buying. But the mortgage payment is where owning's monthly cost starts, not where it ends. The county bills you property tax whether or not you remember it exists. The insurance is required by the lender and priced by the roof. And the house itself charges a fee for existing, which is called maintenance and never appears on any statement until it appears all at once." },
        { kind: "receipt", title: "A $1,700 Payment, Finished", lines: [
          { label: "Mortgage payment", value: "$1,700", note: "illustrative; rates change, so get a real quote" },
          { label: "Property tax", value: "$310", note: "the county's cut, forever, and it gets reassessed" },
          { label: "Homeowner's insurance", value: "$140", note: "required by the lender, rising most years" },
          { label: "Maintenance reserve", value: "$250", note: "about one percent of the price a year, saved in advance", tone: "warn" },
        ], total: { label: "What owning actually costs monthly", value: "$2,400" }, caption: "Illustrative numbers for a $300,000 house; look up your own county, quotes and rates. And early in the loan most of that $1,700 is interest. If only about $350 of it is principal, roughly $2,050 of this is gone money, against rent that is all gone money." },
        { kind: "p", text: "That last line deserves a name: amortization, the schedule that splits every mortgage payment between interest and principal. Early in a long loan the split is lopsided toward interest, and it shifts toward principal slowly over the years. So the equity story your uncle told is real, but it is a slow story, and in the years that matter most for a first-time buyer, the payment is mostly rent you pay to a bank instead of a landlord." },
        { kind: "h", text: "The Toll Booth At Both Ends" },
        { kind: "p", text: "Now the part that decides most cases: buying charges a large fixed fee at the door on the way in, and a larger one on the way out. Going in, closing costs commonly run somewhere around 2 to 5 percent of the price, covering the loan fees, title work, taxes and the rest of the signing-table pile. Going out, selling costs more, because agent commissions, transfer taxes and the repairs a buyer negotiates all come out of your side. The exact percentages move around and some are negotiable, so look up what they run in your state. What does not change is the shape: two toll booths, both expensive, and every dollar paid at them is unrecoverable." },
        { kind: "timeline", title: "One Buyer's Break-Even", points: [
          { at: "Day 1", label: "Down the entry costs", note: "$9,000 in closing costs on a $300,000 house", tone: "warn" },
          { at: "Year 2", label: "Still behind", note: "principal and price growth have not covered the doors yet", tone: "warn" },
          { at: "Year 6", label: "About even", note: "in this example; your doors and your gap set your year" },
          { at: "Year 10", label: "Clearly ahead", note: "equity, and a payment rents have long since passed", tone: "good" },
        ], caption: "Illustrative. The shape is the point: a big fixed cost in, a bigger one out, and years in between to earn them back." },
        { kind: "p", text: "This is why every version of the rent-or-buy answer contains the phrase \"it depends how long you stay.\" The tolls are fixed; the time you have to earn them back is not. Instead of memorizing someone's five-year rule, estimate your own number, because a cheap market with low fees and a big gap in owning's favor breaks even fast, and an expensive market can take a decade." },
        { kind: "steps", title: "Estimate Your Break-Even", steps: [
          { label: "Price both doors", text: "Add roughly 2 to 5 percent of the price for buying and more for selling. Look up what closings and commissions actually run where you live." },
          { label: "Finish both monthlies", text: "Your rent as it stands, against the interest portion of the mortgage plus tax, insurance and a maintenance reserve for the house you would really buy." },
          { label: "Divide and see", text: "Doors divided by the monthly amount owning saves you is years to break even. If owning's gone money is higher than your rent, only principal and price growth can earn the doors back, and price growth is a guess." },
          { label: "Answer the honest question", text: "Will you still be in this house, this job and this city that many years from now? A guess is fine. A shrug is also an answer, and it is not \"buy.\"" },
        ] },
        { kind: "divider" },
        { kind: "h", text: "The Ticket Price Myth" },
        { kind: "p", text: "People treat the down payment as the price of admission: save it and you are ready. The down payment is the biggest line, but it buys you exactly none of the other things the first month of ownership demands, and most of them are due in cash, in the same two weeks, right after your savings took the largest single hit of your life." },
        { kind: "list", title: "Cash the down payment does not cover", items: [
          "Closing costs land at the signing table on top of everything you put down, not inside it.",
          "The inspection and the appraisal are paid up front, and you pay them even on houses you end up walking away from.",
          "Moving costs real money, and it arrives the same week as everything else on this list.",
          "The first ninety days find every problem the seller had learned to live with: a locksmith, a dying fridge, a mystery leak.",
          "A house has more rooms than your apartment did, and empty rooms have a way of ordering furniture.",
        ] },
        { kind: "p", text: "Two more things people underestimate. First, maintenance is not a tidy monthly bill; it averages something like one percent of the house's value a year, but it arrives as a $6,000 roof in a random March, which is why the reserve has to be a funded account and not a mood. Second, the down payment has an alternative job. Forty thousand dollars in a house is forty thousand dollars that is no longer invested and compounding, and whatever it would plausibly have earned belongs in the comparison. That is not an argument against ever buying. It is a line item, and honest math includes it." },
        { kind: "h", text: "The Part That Is Not Money" },
        { kind: "p", text: "Now the side the spreadsheet crowd waves away, wrongly. Owning buys things that are hard to price and completely real: nobody can decline to renew your lease, nobody can sell the building out from under you, you can paint a wall at midnight, put a dog in the yard, and know roughly what your housing costs in year ten, with the honest caveat that taxes and insurance still climb. If you have ever gotten a sixty-day notice you did not want, you know that security is not sentimental. It is worth actual dollars, and how many is yours to decide." },
        { kind: "quote", text: "Rent is the price of a roof. Interest is the price of a roof. Neither one is thrown away, and only one of them lets you leave in thirty days.", who: "Imani, 15th Grade" },
        { kind: "p", text: "Renting's non-financial side is just as real: a thirty-day exit for a better job or a failing relationship, repairs that are a phone call instead of a weekend and a credit card, and no risk of the market picking the year you have to sell. The grown-up move is not to pretend these things away on either side. Put a monthly dollar figure on what stability is worth to you, or what flexibility is worth to you, and add it to the ledger. It belongs in the math, not floating above it." },
        { kind: "h", text: "The Milestone Trap" },
        { kind: "p", text: "Here is the trap this unit exists to kill. Around your late twenties, buying starts to feel less like a transaction and more like a rite: your feed fills with keys held up in front of doors, your parents start asking, and somewhere in there the purchase stops being about housing and becomes proof of adulthood, on a clock set by other people's weddings and closings. The opposite slogan is a trap too; the internet is full of people who turned \"renting wins\" into its own religion. Both crowds are outsourcing a six-figure decision to a vibe. What buying on the milestone actually costs, in behavior: people buy in cities they are lukewarm on, at the top of their approval, two years before a move they could have predicted, and then pay both toll booths on a forced sale or become a reluctant landlord in a city they left." },
        { kind: "callout", title: "The rule", text: "Buy when your break-even is comfortably shorter than the time you would stay anyway, at the full monthly cost, with cash left over after the doors. Any reason for buying this particular year that starts with somebody else's timeline is not a reason." },
        { kind: "example", title: "Worked example: Marcus and the two doors", text: "Marcus is 26, an HVAC tech in Columbus, paying $1,250 for a one-bedroom. At his cousin's housewarming his uncle does the speech, and it lands: within six weeks Marcus is preapproved and under contract on a $260,000 house with a quoted payment of about $1,480, close enough to his rent that it felt free. He paid $450 for the inspection and put down $600 in earnest money before he ever finished the receipt. When he finally ran it, owning came to about $2,250 a month with tax, insurance and a maintenance reserve, and with early payments mostly interest, roughly $1,950 of that was gone money against $1,250 of rent. Both doors together came to something like $23,000, a break-even of about six years, and his girlfriend was applying to nursing programs in three states. He walked. The earnest money came back under the inspection contingency; the $450 did not, and it stung for exactly one week, which is how long it took him to price what selling in year two would have cost instead. Three years later, married and settled in Indianapolis with a job he plans to keep for a decade, the same receipt pointed the other way, and he bought. The maintenance line was already a funded account, because the water heater does not care that you just closed." },
        { kind: "bigfact", stat: "$23,000", caption: "the two toll booths on Marcus's almost-house: what a forced sale in year two would have burned in entry and exit costs alone." },
        { kind: "p", text: "So no, rent is not throwing money away, and neither is interest. They are both the price of a roof, paid to different people, with different things attached. Run the receipt, price the doors, name your years, and let the smaller pile win. The uncle at the housewarming never did the math. You just did." },
      ],
      takeaways: [
        "Renting and owning both cost money you never get back; the honest comparison is between the two piles of unrecoverable cost, not between rent and a mortgage payment.",
        "A mortgage payment equal to your rent is not the same cost: property tax, insurance and maintenance come on top, and early payments are mostly interest.",
        "Only the principal slice of a mortgage payment becomes equity, and early in a long loan it is the small slice.",
        "Buying charges a large fixed cost at the door in and a larger one at the door out, so how long you stay decides who wins the math.",
        "Estimate your own break-even by dividing both doors by the monthly amount owning saves you, instead of repeating anyone's rule of thumb.",
        "The down payment is not the ticket price: closing costs, inspection, moving and the first repairs are all cash on top, due around the same weeks.",
        "Maintenance averages about one percent of the house's value a year but arrives in lumps, so it needs a funded account, not a shrug.",
        "A down payment has an alternative job, and whatever it would plausibly have earned invested belongs in the comparison.",
        "Stability and control are worth real dollars and so is flexibility; price them yourself and add them to the ledger, and never buy on a clock set by other people's milestones.",
      ],
      theLesson: "Renting and owning both burn money every month, so compare the unrecoverable costs of each over the years you will honestly stay, and buy on that arithmetic instead of on a proverb or a milestone.",
      quiz: [
        {
          q: "Your uncle says rent is throwing money away. The accurate reply is...",
          options: [
            "So is mortgage interest, and so are property tax, insurance and upkeep",
            "Rent buys flexibility, so it is actually the smarter move in every market",
            "He is right, which is why buying should happen as early as possible",
            "Rent only counts as wasted when it is higher than the local mortgage",
          ],
          answer: 0,
          explain: "Both ways of paying for a roof burn money monthly, so the fair fight is unrecoverable costs against unrecoverable costs. Answering that renting is \"the smarter move in every market\" is tempting because it feels like the corrective, but it just swaps one slogan for the opposite one.",
        },
        {
          q: "The mortgage payment on a house you like exactly equals your rent. That means...",
          options: [
            "Owning costs the same, so the equity makes it the better deal",
            "Owning costs more once tax, insurance and maintenance join the bill",
            "Owning costs less, because part of every payment comes back to you",
            "Nothing yet, until you know which way local prices are heading",
          ],
          answer: 1,
          explain: "The payment is where owning's cost starts, not where it ends. The idea that part of every payment \"comes back to you\" is tempting because principal is real, but early in a long loan the principal slice is small, and tax, insurance and maintenance are pure additions with no equity in them.",
        },
        {
          q: "Why does time in the house matter so much to the rent or buy answer?",
          options: [
            "Because prices reliably rise if you can hold on long enough",
            "Because lenders reward longer ownership with lower rates",
            "Because buying charges big fixed fees on the way in and out",
            "Because rent climbs every year while a mortgage never moves",
          ],
          answer: 2,
          explain: "The toll booths at both doors are fixed costs, and only years of ownership earn them back. \"Prices reliably rise\" is the tempting one, but nobody guarantees your market over your window. And a mortgage payment is not frozen either: taxes and insurance climb even on a fixed-rate loan.",
        },
        {
          q: "Amara saved a $30,000 down payment and calls herself ready to buy. What is she forgetting?",
          options: [
            "That a bigger down payment would get her a much better rate",
            "That the money should be earning interest until closing day",
            "Closing costs, inspection, moving and first repairs, in cash on top",
            "Nothing, since the other costs of buying roll into the payment",
          ],
          answer: 2,
          explain: "The down payment is the biggest line, not the whole ticket. \"The other costs roll into the payment\" is the tempting one because some closing costs sometimes can be financed, but the inspection, the move and the first repairs cannot, and financing fees means paying interest on them for decades.",
        },
        {
          q: "What is the alternative job of a down payment?",
          options: [
            "Sitting in savings as the emergency fund for the new house",
            "Paying the mortgage down faster to shorten the loan term",
            "Covering the closing costs so nothing extra is ever needed",
            "Staying invested and compounding, which buying makes it give up",
          ],
          answer: 3,
          explain: "Money parked in a house is money no longer invested, and whatever it would plausibly have earned belongs in the comparison. \"The emergency fund for the new house\" is tempting because a reserve is genuinely needed, but that is a separate account; the down payment itself is spent on day one.",
        },
        {
          q: "The clearest sign someone is buying on the milestone and not the math is...",
          options: [
            "They picked a thirty-year loan when a fifteen-year one was open to them",
            "They cannot name how long they will stay, yet everyone they know just bought",
            "They are buying a smaller place than the ones their friends bought",
            "They negotiated hard on price instead of accepting the listing number",
          ],
          answer: 1,
          explain: "The tell is a purchase clock set by other people's lives paired with a shrug at the staying question, because time in the house is what earns back the doors. A thirty-year loan is just a term choice, and negotiating hard on price is what buying on the math actually looks like.",
        },
      ],
      cards: [
        { front: "Unrecoverable cost", back: "Money that buys you the month and nothing else. For a renter it is the rent. For an owner it is mortgage interest, property tax, insurance, maintenance and the fees at both doors." },
        { front: "Finish the payment", back: "A mortgage payment is where owning's monthly cost starts, not where it ends. Add property tax, insurance and a maintenance reserve before comparing anything to rent." },
        { front: "Amortization", back: "The schedule splitting each mortgage payment between interest and principal. Early in a long loan most of the payment is interest, so the equity slice starts small and grows slowly." },
        { front: "The two doors", back: "Buying charges roughly 2 to 5 percent of the price on the way in and more on the way out. Staying long enough to earn both back is the whole game; look up the local figures." },
        { front: "Break-even estimate", back: "Add both doors, then divide by the monthly amount owning saves you. The answer is years. Compare it to how long you would honestly stay, not to a rule of thumb." },
        { front: "The ticket price myth", back: "The down payment is not the full cost of entry. Closing costs, inspection, appraisal, moving and the first repairs are all cash on top, due around the same weeks." },
        { front: "Maintenance is lumpy", back: "Plan on about one percent of the house's value per year, but it arrives as a $6,000 roof in a random March, not a tidy bill. Fund the reserve before the house needs it." },
        { front: "The down payment's other job", back: "Money in a down payment could have stayed invested and compounded. Whatever it would plausibly have earned belongs in the rent or buy comparison as a real line item." },
        { front: "The milestone trap", back: "Buying because it feels like proof of adulthood, on a clock set by other people's weddings and closings. The only inputs that matter are your numbers and your years." },
      ],
      action: "Tonight, run the receipt on one real listing you could imagine buying: an online mortgage calculator for the payment, the listed property tax, an insurance estimate, and one percent of the price divided by twelve for maintenance. Put the total next to your rent, then write down your honest answer to one question: how many years would I stay?",
    },
    "partner-money-talks": {
      hook: "Couples fight about money more than anything else and talk about it less than anything else. The fight was never about the number.",
      blocks: [
        { kind: "p", text: "Sunday night, 9:40. Jess is holding her phone like evidence. On the screen is the credit card app and a $212 charge from a golf store, and Marcus is explaining that he bought the shoes with his own money, and Jess is saying there is no such thing as his own money anymore, and both of them are getting louder about a number neither of them will remember in a year. Neither of them can see this from inside the kitchen. Jess grew up in a house where a parent hid bills in the glove compartment and the electricity got shut off twice. Marcus grew up in a house with a budget spreadsheet taped to the fridge and an allowance that arrived like a paycheck. She sees an unannounced purchase and feels the floor move. He hears an audit and feels sixteen again. They are not arguing about a budget. They are arguing about what money is for, and neither of them knows it." },
        { kind: "p", text: "Money holds a strange title in relationships: the thing couples fight about most and talk about least. Most couples are running a financial system nobody chose, under rules nobody said out loud, written by four parents who never met. This unit is about saying the rules out loud, in three conversations, starting with the one almost nobody has had." },
        { kind: "h", text: "Not About the Number" },
        { kind: "p", text: "Every money fight has two layers. The surface layer is a number: the shoes, the subscription, the takeout order. The real layer is one of three things: safety, fairness, or freedom. Am I protected if this goes wrong? Are we both carrying this? Do I still get to be a person with my own choices? Which of those a purchase touches depends entirely on the house you learned money in. A partner raised on shutoff notices reads a surprise charge as danger. A partner raised on the fridge spreadsheet reads a question about it as surveillance. Same charge, same question, two alarms going off in two different childhoods." },
        { kind: "split", title: "What Gets Said vs. What Is Meant", leftLabel: "The line out loud", rightLabel: "The line underneath", rows: [
          { left: "You spent WHAT on shoes?", right: "Spending I didn't see makes me feel unsafe" },
          { left: "It's my money, I earned it", right: "I need some freedom that isn't supervised" },
          { left: "Why am I the only one who checks the account?", right: "Carrying this alone feels unfair" },
          { left: "We can't afford that", right: "That kind of spending scares me and I can't say why" },
          { left: "Your parents again?", right: "I don't know what the rules are about family and money here" },
        ] },
        { kind: "p", text: "This is why the same fight repeats even when the amounts are small. You can win the argument about the shoes and lose it again next month about a concert ticket, because the shoes were never the subject. The only durable fix is to get the bottom layer into the open on purpose, in calm weather. That is what the three conversations are for." },
        { kind: "h", text: "The Three Conversations" },
        { kind: "p", text: "History, facts, future. Each one has its own timing and its own opening line, and they go in this order because each one makes the next one survivable. Do them out of order, facts before history, and the numbers land without context: a debt is just a debt instead of the end of a story you understand." },
        { kind: "steps", title: "In This Order", steps: [
          { label: "History", text: "What money felt like in the house each of you grew up in. No numbers, no documents, no judgment. This is the one almost nobody has, and it explains everything else." },
          { label: "Facts", text: "Full disclosure: income, every debt, credit scores, and standing obligations like family support. This happens before anything merges, and somebody has to go first." },
          { label: "Future", text: "Where you will live, whose career leads when they conflict, parents, children, and what retirement even means to each of you. This one gets revisited every year." },
        ] },
        { kind: "p", text: "History opens with one question: \"What did money feel like in your house growing up?\" Feel like, not look like. You are not asking for their parents' salaries. You are asking whether money was discussed at the table or only fought about behind a door, whether asking for things was normal or dangerous, who handled the bills and what happened when they couldn't. Have it early, in the first few months, because it is genuinely pleasant. Almost nobody gets asked this, and the answer is the operating manual for every money reaction your partner will ever have." },
        { kind: "p", text: "Facts is the one people dodge, and shame is the reason. The average person would rather show a partner their search history than their credit score. So debt hides, and hidden debt does not stay a number: it becomes a secret, and the secret does more damage than the balance ever could. Full disclosure comes before anything merges: before a shared lease, a shared account, a loan with both names on it. You are not entitled to a stranger's finances. You are both entitled to the full picture before your signatures start appearing on the same documents." },
        { kind: "callout", title: "I'll go first", text: "The facts conversation has a magic phrase, and it is \"I'll go first.\" Then actually go first: your income, your debts, your score, your obligations, before you have seen any of theirs. Disclosure feels like standing on a ledge. Going first means your partner steps out to join you rather than being pushed. If you go first with everything and get evasion back, that is not a scheduling problem. That is information." },
        { kind: "p", text: "Future is the conversation about the shape of the life. Where will you live, and what happens if one of you gets an offer somewhere else? When both careers can't lead, whose does, and does it rotate? Is supporting parents an expectation, and what does it cost monthly? Children or not, and who slows down if so? What does retirement even mean to each of you, a paid-off house at 55 or working forever by choice? Nobody answers all of these at once. The point is that neither of you is quietly certain about something the other has never heard." },
        { kind: "timeline", title: "When Each Talk Belongs", points: [
          { at: "Month 1 to 6", label: "History", note: "Casual, early, no documents. A walk, a drive, a slow dinner.", tone: "good" },
          { at: "Before a lease", label: "Facts, round one", note: "Incomes and rough obligations, before your names share paper." },
          { at: "Before merging money", label: "Facts, in full", note: "Every debt, both scores, everything recurring. I'll go first." },
          { at: "Before rings or mortgages", label: "Future", note: "Careers, parents, children, retirement. Revisit every year after.", tone: "good" },
        ], caption: "The thresholds are the trigger. Each time the relationship is about to cross one, the matching conversation comes first." },
        { kind: "divider" },
        { kind: "h", text: "Three Ways to Build It" },
        { kind: "p", text: "Couples run money three basic ways, and none of them is the right one. Each is good at something and bites somewhere, and couples thrive and fail inside all three. What predicts trouble is not the structure. It is a partner who does not understand it, or never agreed to it." },
        { kind: "table", title: "The Three Structures", head: ["Structure", "Good at", "Where it bites"], rows: [
          ["Fully separate", "Autonomy, clean if it ends", "Endless splitting, invites scorekeeping"],
          ["Fully joint", "Simple, transparent, one team", "No private margin, income gap felt daily"],
          ["Shared + own, proportional", "Fair at unequal incomes, keeps privacy", "More accounts, needs real upkeep"],
          ["Shared + own, 50/50", "Feels equal, easy math", "Flat split eats the lower earner alive"],
        ], caption: "The right structure is the one both of you can explain without the other one correcting you." },
        { kind: "p", text: "The common middle deserves one note on arithmetic. A shared account covers shared life: rent, groceries, utilities. Each person keeps their own account, no questions asked. The contribution should usually be proportional to income, because a 50/50 split at unequal incomes quietly makes the shared life a luxury the lower earner funds with their entire margin. If one of you earns $60,000 and the other $40,000, sixty and forty percent of the shared costs leaves both people with real money of their own. Equal dollars would leave one of you free and the other broke, in the same apartment." },
        { kind: "h", text: "What Goes Wrong" },
        { kind: "list", title: "The four classic failures", items: [
          "The income gap becomes a power gap: the higher earner starts holding vetoes nobody voted on, and the lower earner starts asking permission for things that used to be choices.",
          "One partner's debt becomes a secret, and the secret compounds faster than the interest does.",
          "Financial infidelity: hidden accounts, hidden cards, hidden spending. It is called infidelity because it is discovered like one and grieved like one.",
          "One person handles everything, and the other could not name the bills, find the accounts, or run their own life if the handler left or died.",
        ] },
        { kind: "p", text: "The power gap is the quiet one, because it arrives disguised as generosity. \"I make more, so I'll cover more\" is a kind sentence, and then a year later the person covering more has somehow become the person who approves things. Nobody decided this. It condensed, the way fog does. The fix is structural, not moral: proportional contributions and a no-questions personal account for each partner mean the lower earner never has to request their own freedom, so the gap in income never gets the chance to become a gap in standing." },
        { kind: "p", text: "The last failure on that list deserves its own paragraph, because it usually comes from love. One partner is good with money, so they take it over, and the other gratefully lets them. Ten years later one of them is sitting in a bank branch after a funeral, unable to name the accounts, or sitting in a lawyer's office during a divorce, discovering what the household actually owed. The fix costs one evening twice a year: both partners can log in everywhere, both know what exists and what it costs to run, and once in a while the one who never drives the money drives it for a month." },
        { kind: "quote", text: "We never once fought about money. It turned out we had never once talked about it either.", who: "Alina, 15th Grade" },
        { kind: "h", text: "The Spreadsheet Trap" },
        { kind: "callout", title: "The trap", text: "Hearing all this, the organized partner opens a laptop, categorizes six months of the other's spending, and schedules a meeting. That is not a money conversation. That is a performance review, and nobody in history has responded to a surprise performance review by opening up." },
        { kind: "p", text: "A spreadsheet turned toward your partner reads as prosecution: here is the evidence, explain yourself. Their spending was never a data problem, it was a meaning problem, and a pivot table cannot see meaning. The couch conversation about what money felt like at nine years old will change more spending behavior than any chart. Build the spreadsheet later, together, both of you facing the same screen, once the three conversations have made it a tool instead of an indictment." },
        { kind: "h", text: "The Cost of Skipping It" },
        { kind: "p", text: "Dre and Sam merged everything at month four. One account, both paychecks, total transparency, very romantic. By year two they were unpicking it: new accounts, redirected deposits, eighteen months of tangled transactions, and a card balance neither could fully claim, separated one awkward transfer at a time. Merging everything was not their mistake. Merging it before either of them knew what money meant to the other was, because every difference in the two childhoods got discovered inside a joint account, live, with real dollars, instead of in a conversation where nothing was at stake." },
        { kind: "p", text: "Kayla and Ross went the other way: six years together and never one real money conversation, because things were good and why poke it. Then a mortgage application put both of their lives on one table, and a loan officer, a stranger with a name tag, was the one who told Kayla about the $31,000 in loans and the 580 credit score. The mortgage was gone, and that was the small loss. The large one was that six years of \"we're good\" turned out to mean \"we never checked,\" and rebuilding that took longer than fixing the score did." },
        { kind: "example", title: "Worked example: Nadia and Eric", text: "Nadia, 24, hospital scheduler, $61,000. Eric, 25, apprentice electrician, $44,000. They decide to move in together, and Nadia suggests the facts conversation. Eric dodges it twice, because Eric is carrying $9,400 on a card at 26 percent interest and is ashamed of every dollar. Nadia finds a statement in a coat pocket, and it goes exactly as badly as you would guess, for about a week, mostly because of the hiding. The recovery starts when Nadia opens the full-disclosure night with her own numbers first: $18,000 in student loans, a 690 score, $150 a month to her grandmother, non-negotiable. Eric follows with the card and a 640 score. Then they build the middle structure. Shared costs are $2,600 a month: $1,850 rent, $210 utilities, $460 groceries, $80 internet. Nadia earns 58 percent of their combined income, so she puts in $1,508 and Eric puts in $1,092, and each keeps their own account, no questions asked. The split is what makes the debt plan work: Eric's card stays Eric's problem, but paying $1,092 instead of $1,300 leaves him room to throw $450 a month at it. Just under two years later it is gone. The debt was never the danger. The coat pocket was." },
        { kind: "bigfact", stat: "3 talks", caption: "One about the past, one about the present, one about the future, each under an hour. They replace the one fight that otherwise runs for years." },
      ],
      takeaways: [
        "Money is the thing couples fight about most and talk about least, and the fight is almost never about the number on the screen.",
        "Under every money fight is safety, fairness, or freedom, and which one fires depends on what money did in the house each partner grew up in.",
        "The history conversation, what money felt like growing up, is the one almost nobody has, and it is the operating manual for every reaction that follows.",
        "The facts conversation is full disclosure of income, debt, credit, and obligations, and it belongs before anything merges: a lease, an account, a loan.",
        "Saying \"I'll go first\" and disclosing your own numbers before seeing any of theirs is what makes disclosure survivable for a partner carrying shame.",
        "Fully separate, fully joint, and shared-plus-own all work and all bite; what predicts trouble is one partner not understanding or never agreeing to the structure.",
        "An income gap turns into a power gap quietly, through cover-more generosity that hardens into approval rights, unless proportional contributions and personal accounts block it.",
        "If one person runs all the money, the other is one funeral or one breakup away from being lost inside their own life; both partners should be able to drive.",
        "A spreadsheet of your partner's spending is a fine tool to build together later and a reliable way to end the conversation if you open with it.",
      ],
      theLesson: "Money fights are about what money means, not what it costs, so have the three conversations, history, facts, and future, before your lives merge instead of after something breaks.",
      quiz: [
        {
          q: "A couple keeps having the same fight about small purchases. What is the fight usually about?",
          options: [
            "The purchases themselves: small recurring leaks genuinely sink shared budgets over time",
            "Personality: one of them is a spender, and a spender and a saver cannot share accounts",
            "What money means: safety, fairness, and freedom, learned in two different childhood houses",
            "Bad timing: reviewing the account at the end of the month guarantees a monthly argument",
          ],
          answer: 2,
          explain: "The number is the surface layer. \"Small recurring leaks\" is tempting because leaks are real, but winning the fight about the shoes changes nothing, since next month the same alarm fires about a concert ticket. The fight repeats because it is about safety, fairness, or freedom, and those were learned long before the couple met.",
        },
        {
          q: "Which conversation does this unit say almost nobody has, and why does it come first?",
          options: [
            "History: what money felt like growing up, because it explains every reaction that follows",
            "Facts: full disclosure of debt and credit, because everything else is built on real data",
            "Future: careers and retirement, because long-range plans reveal values faster than pasts",
            "Structure: how the accounts get set up, because the system ends up shaping the behavior",
          ],
          answer: 0,
          explain: "\"Full disclosure of debt and credit\" is tempting because facts feel urgent, but numbers without context land as bare judgment: a debt is just a debt. History comes first because it is the interpreter. Once you know what money did in your partner's childhood house, you know what their numbers, and their reactions, actually mean.",
        },
        {
          q: "When does the facts conversation, full disclosure of income, debt, and credit, belong?",
          options: [
            "Once you are engaged, since asking much earlier reads as mistrust of a newer partner",
            "Whenever a big purchase forces the issue, because context makes hard numbers land softer",
            "After a year together, once the relationship has proven that it can survive hard news",
            "Before anything merges: a lease, an account, a loan, anything carrying both of your names",
          ],
          answer: 3,
          explain: "\"Once you are engaged\" is the expensive one: by then the merging has usually already begun, and Kayla learned Ross's numbers from a loan officer. You are not entitled to a stranger's finances, but before your signatures start sharing documents, you are both entitled to the full picture. The threshold is the merge, not the milestone.",
        },
        {
          q: "What does this unit conclude about the ways couples can structure their money?",
          options: [
            "Shared-plus-own is the winner, because it balances fairness against personal privacy",
            "The structure matters less than whether both people understand it and chose it out loud",
            "Fully joint is safest, since total transparency leaves no room for any hidden spending",
            "Fully separate is safest, since a clean division protects each person if things end",
          ],
          answer: 1,
          explain: "Shared-plus-own is the common middle and it is tempting to crown it, but couples thrive and fail inside all three structures. Each is good at something and bites somewhere. What predicts trouble is a structure one partner cannot explain or never agreed to, which is why the table's caption is the real answer.",
        },
        {
          q: "Why does opening a money talk with a spreadsheet of your partner's spending backfire?",
          options: [
            "Spreadsheets are imprecise, and broad categories hide what the money actually bought",
            "It skips ahead, since the future conversation has to come before any review of the past",
            "It turns the talk into a performance review, so your partner defends instead of talks",
            "Numbers make people emotional, and money conversations should stay away from feelings",
          ],
          answer: 2,
          explain: "The spreadsheet's precision is not the problem; \"imprecise\" gets it backwards. A laptop turned toward your partner reads as prosecution, evidence first, explain yourself, and nobody answers an indictment with openness. Spending is a meaning problem before it is a data problem. Build the spreadsheet together, later, facing the same screen.",
        },
        {
          q: "One partner runs every bill, account, and password. What is the actual danger there?",
          options: [
            "The other partner cannot run their own life if the handler ever leaves, dies, or hides",
            "The handler will grow to resent the workload and use the accounts as leverage in fights",
            "Nothing, as long as the handler is honest and careful; specialization is how teams work",
            "The system collapses the first month the handler gets too busy to keep it all updated",
          ],
          answer: 0,
          explain: "\"Specialization is how teams work\" is the tempting one, because the arrangement usually starts as a kindness. But a team where one member cannot find the accounts is one funeral or one breakup from disaster, and total control also makes hiding effortless. Both partners need logins, the full map, and an occasional month at the wheel.",
        },
      ],
      cards: [
        { front: "What money fights are about", back: "Safety, fairness, or freedom, almost never the number. Which alarm fires depends on what money did in the house each partner grew up in." },
        { front: "The history conversation", back: "\"What did money feel like in your house growing up?\" Early, casual, no documents. The one almost nobody has, and the operating manual for every money reaction your partner will ever have." },
        { front: "The facts conversation", back: "Full disclosure of income, every debt, credit scores, and standing obligations. It belongs before anything merges: a lease, a joint account, a loan with both names." },
        { front: "I'll go first", back: "The phrase that makes disclosure survivable. Lay out your own income, debts, and score before seeing any of theirs. Going first turns a push off the ledge into a step taken together." },
        { front: "The future conversation", back: "Where you will live, whose career leads in a conflict, supporting parents, children, and what retirement means to each of you. First pass before rings or mortgages, revisited yearly." },
        { front: "The three structures", back: "Fully separate, fully joint, and shared-plus-own. All three work and all three bite. The structure matters less than both partners understanding it and choosing it out loud." },
        { front: "Proportional contributions", back: "Each partner funds shared costs as a percentage of income, not 50/50. Flat splits at unequal incomes eat the lower earner's entire margin and turn the income gap into a power gap." },
        { front: "Financial infidelity", back: "Hidden accounts, hidden cards, hidden debt. Called infidelity because it is discovered like one and grieved like one. The secret usually does more damage than the balance." },
        { front: "The one-handler risk", back: "When one partner runs all the money, the other is one funeral or one breakup from being lost inside their own life. Both need logins, the full map, and occasional turns driving." },
      ],
      action: "Tonight, ask your partner one question: \"What did money feel like in your house growing up?\" No numbers, no documents, and you answer it too. Single? Write your own answer down in three sentences; it is the half of the conversation you can finish now.",
    },
  },
};
