// The 14th Grade: money, mastered. Demo course for review:
// full structure, three units carry complete lessons.

import type { Course } from "./lms";

export const COURSE_14: Course = {
  slug: "the-14th-grade",
  title: "The 14th Grade",
  kicker: "Course Two",
  tone: "vio",
  status: "preview",
  headline: "Money, mastered. Earning it, growing it, keeping it.",
  description:
    "The deeper money course: negotiate what you earn, put it to work, and protect it from taxes, bad products, and scams. 12 units, plain English throughout.",
  parts: [
    {
      id: "earn",
      name: "Earn More",
      tone: "acc",
      tagline: "The fastest raise is the one you ask for.",
      action: "Run one real number from this chapter on your own situation today.",
      units: [
        { slug: "salary-negotiation", title: "Salary Negotiation", blurb: "The script, the silence, and why the first number matters so much.", live: true },
        { slug: "job-offer-math", title: "Job Offer Math", blurb: "Base, bonus, equity, benefits: comparing offers on the full number.", live: false },
        { slug: "side-income", title: "Side Income", blurb: "Turning a skill into a second paycheck without burning out.", live: false },
        { slug: "freelance-basics", title: "Freelance Basics", blurb: "Contracts, invoices, and getting paid on time, every time.", live: false },
      ],
    },
    {
      id: "grow",
      name: "Grow It",
      tone: "vio",
      tagline: "Compounding does the work. You just have to not interrupt it.",
      action: "Open the account or check the fund. One concrete step, today.",
      units: [
        { slug: "index-funds-explained", title: "Index Funds, Actually Explained", blurb: "What you own, what it costs, and why fees decide more than skill.", live: true },
        { slug: "retirement-alphabet", title: "The Retirement Alphabet", blurb: "401(k), IRA, Roth, HSA: which bucket, in which order, and why.", live: false },
        { slug: "brokerage-basics", title: "Brokerage Basics", blurb: "Opening an account, placing your first order, and the settings that matter.", live: false },
        { slug: "risk-and-time", title: "Risk & Time", blurb: "Why your age changes the answer, and what \"risk tolerance\" actually means.", live: false },
      ],
    },
    {
      id: "keep",
      name: "Keep It",
      tone: "coral",
      tagline: "Making money is loud. Keeping it is quiet.",
      action: "Check one account, statement, or policy from this chapter today.",
      units: [
        { slug: "scam-proof", title: "Scam-Proof", blurb: "The scripts scammers use on smart people, and the two-step habit that beats all of them.", live: true },
        { slug: "taxes-level-two", title: "Taxes, Level Two", blurb: "Brackets, capital gains, and the moves that legally shrink the bill.", live: false },
        { slug: "insurance-decoded", title: "Insurance, Decoded", blurb: "What to insure, what to skip, and how deductibles really work.", live: false },
        { slug: "beneficiaries-and-wills", title: "Beneficiaries & Wills", blurb: "The one-page folder your family hopes you have.", live: false },
      ],
    },
  ],
  lessons: {
    "salary-negotiation": {
      hook: "Ninety seconds of scripted discomfort, paid out on every paycheck for the rest of your career.",
      blocks: [
        { kind: "p", text: "Minute six of a thirty minute phone screen. Maya, 23, has answered two easy questions about her background when the recruiter says, pleasantly, \"Just so we're aligned, what are your salary expectations?\" Her mind goes white. Her current job pays $52,000, she does not want to seem greedy, and the pause is getting long, so she says \"maybe around $58,000?\" with a question mark on the end. The recruiter types something and moves on. Nothing bad happened. Nothing bad ever appears to happen. But the ceiling of the entire negotiation was just set, in minute six, in a conversation Maya thought had not started yet." },
        { kind: "p", text: "This unit is the choreography of a salary conversation, start to finish, with the actual words. The 13th Grade taught you to negotiate rent, bills and scope. Salary is a different animal: the person across from you does this professionally, the number compounds for decades, and the exchange runs on a script published nowhere and known, usually, by one side. By the end of this page you are on the side that knows it." },
        { kind: "h", text: "Why the First Number Wins" },
        { kind: "p", text: "Every negotiation orbits its first number. Name $58,000 and the conversation becomes $58,000 plus or minus a little, no matter what the company had penciled in. This is anchoring: the first number on the table drags every later number toward it, even when both sides know it was a nervous guess. It works on trained recruiters. It works on you. The defense is making sure the first number belongs to the side holding the real information." },
        { kind: "p", text: "Here is the part that changes how the room feels. The person you are negotiating with almost never set the number and is not spending their own money. Somewhere upstream, finance approved a band for the role, say $65,000 to $78,000 for the job Maya wants, and the recruiter's assignment is to fill the seat inside it, ideally toward the bottom. Your counter is not a confrontation. It is a Tuesday. A calm, researched ask is something they have seen a hundred times and respect." },
        { kind: "receipt", title: "What $5,000 at 23 Becomes", lines: [
          { label: "Starting gap at 23", value: "$5,000", note: "Two identical hires; one countered, one said thank you" },
          { label: "Yearly gap at 30", value: "$6,149", note: "The same gap after seven ordinary 3 percent raises", tone: "warn" },
          { label: "Yearly gap at 40", value: "$8,264", note: "Still compounding, with no extra work by anyone", tone: "warn" },
        ], total: { label: "Extra earned by 40", value: "$108,000" }, caption: "Illustrative: two identical careers, 3 percent raises, no promotions or job changes. Seventeen years of percentages, all taken on a base that one conversation set." },
        { kind: "h", text: "Never Go First" },
        { kind: "p", text: "So the expectations question gets answered with a question. The words: \"I'd rather make sure the role is a fit before we get into numbers. Can you share the range that's been budgeted for the position?\" A growing number of states require companies to post that range, so asking is ordinary, and recruiters usually have it on the screen. If they press, hold once more: \"I'm flexible for the right role. What does the band look like on your side?\" If they push a third time, give a range, not a single number, with a bottom you would genuinely accept, because the bottom is the only part they will hear." },
        { kind: "p", text: "Application forms are the one place you cannot deflect. Some will not submit without digits in the salary field. Type the top of your researched range. The form is a filter, not a contract, and it can only hurt you in one direction. A high number can be talked down gracefully in person. A low one becomes the anchor, and nobody will ever tell you it did." },
        { kind: "split", title: "The Same Moment, Two Scripts", leftLabel: "What most people say", rightLabel: "What works", rows: [
          { left: "\"What are your expectations?\" \"Um, maybe $58,000?\"", right: "\"What range has been budgeted for this position?\"" },
          { left: "The form wants a number, so you type your current salary", right: "Type the top of your researched range; forms only anchor down" },
          { left: "Offer lands: \"Wow, thank you, that works!\"", right: "\"Thank you, I'm excited. Could I take two days to review it?\"" },
          { left: "\"I was hoping for a bit more, but honestly it's fine\"", right: "\"Based on the scope and the market, I was expecting closer to $72,000\"" },
          { left: "After your number: keep talking, explaining, softening", right: "After your number: stop. The silence is doing the work" },
        ] },
        { kind: "h", text: "Research a Real Range" },
        { kind: "p", text: "A number you can defend beats a number you merely deserve. Three kinds of sources are worth something. First, posted ranges on listings: some states require them, so search your exact title in Colorado, California, New York or Washington even if you live elsewhere. Second, aggregate sites like Glassdoor, Levels.fyi and Payscale, which are noisy one at a time and useful in chorus; where two of them and a posted range agree, you have found the market. Third, people a year or two ahead of you in the same job. Do not ask what they make. Ask \"would $72,000 be out of line for someone with my experience?\" That version gets answered far more often, and the answer is worth more than any website." },
        { kind: "list", title: "Your research must produce", items: [
          "A floor: the number below which you will politely walk away, decided before any call, because a floor chosen mid conversation always sinks.",
          "A target: the number you will actually ask for, sitting near the top of what your evidence supports.",
          "Three data points you can say out loud if anyone asks where your number comes from.",
          "The band itself, if a posting or a person handed it to you, because then you are playing with the map face up.",
        ] },
        { kind: "h", text: "The Ask and the Silence" },
        { kind: "p", text: "You do not negotiate on the offer call, and you do not accept on it, no matter how good the number sounds. The words: \"Thank you, I'm really excited about this. Could I take a couple of days to review the details?\" Then the counter, on a call you scheduled, in four beats. Enthusiasm first: \"I want to be here, and I'm hoping we can make the numbers work.\" The ask: \"Based on the scope of the role and what I'm seeing in the market, I was expecting something closer to $72,000.\" One reason, your strongest: a skill, a result, a competing conversation if you truly have one. Then nothing." },
        { kind: "bigfact", stat: "48 hrs", caption: "Ask for them before answering any offer. \"I'd like two days to review the details\" has never read as ingratitude to anyone worth working for." },
        { kind: "p", text: "That silence is neither empty nor rejection. The recruiter is looking at the band, doing arithmetic, deciding what to take back to the hiring manager. Your job is to let it happen. Every word you add is a bid against yourself: \"but I understand if that's not possible\" donates real dollars in nine syllables. Count the seconds silently if you have to. Someone will speak, and it should not be you." },
        { kind: "quote", text: "The silence after my number felt like a month. On the recording it was nine seconds. Nine seconds, seven thousand dollars.", who: "Maya, 14th Grade" },
        { kind: "divider" },
        { kind: "h", text: "Offer Versus Raise" },
        { kind: "p", text: "Those two conversations wear the same word and run on different fuel. At offer time your leverage is at its lifetime peak with this employer: they screened dozens of people, spent weeks and real money choosing you, and the alternative to a small yes is starting the whole search over. You will never have this much leverage with them again, which is why the counter is not optional." },
        { kind: "p", text: "A raise inside a job runs on documented results, the cost of replacing you, and timing. Your manager usually cannot say yes alone; they carry a case upstairs, so write the case for them. One page: what you took on, what it produced, what the market pays for the work you now do. Then the ask: \"Based on this, I'm asking for $72,000. What would it take to get there?\" Budgets are usually set months before reviews happen, so raise the subject a quarter early, before the pool has been divided." },
        { kind: "h", text: "Negotiate the Package" },
        { kind: "p", text: "Base is the hardest lever because the band has walls and an owner. When base stalls, the conversation is not over: most of the package lives outside the band and is much easier for a manager to move." },
        { kind: "table", title: "The Levers, Ranked by Give", head: ["Lever", "How movable", "Why"], rows: [
          ["Start date", "Almost always", "Costs the company nothing"],
          ["Signing bonus", "Usually", "One-time money sits outside the band"],
          ["Remote days", "Often", "Usually the manager's own call"],
          ["Review timing", "Often", "A promise now, money later"],
          ["Title", "Sometimes", "Free, but politics attach to it"],
          ["Base salary", "Hardest", "The band has walls and an owner"],
        ], caption: "When the base is capped, work down this list from the top." },
        { kind: "p", text: "The line that opens all of it: \"If the base is fixed for this cycle, is there room on a signing bonus, or an early review with a defined raise?\" A six month review with written criteria and a named number is a raise on layaway, and companies agree to it far more readily than they move base, because the money is next year's problem." },
        { kind: "h", text: "The Fear, and the No" },
        { kind: "callout", title: "Real talk", text: "The fear underneath all of this is that asking makes the offer vanish. At a company worth joining, it essentially does not happen: the people who hire know negotiation is part of hiring, and a reasoned counter reads as competence, not greed. Offers get pulled over rudeness, dishonesty and long unexplained silences, not over one researched number delivered warmly. And if a company ever does pull an offer for that, it just showed you, before your first day and at zero cost, exactly how it treats people who ask for things. Most people pay years to learn that." },
        { kind: "p", text: "Sometimes the answer is no and the no is real. The band is the band, the bonus pool is empty, the manager is out of moves. The line for that moment: \"Understood. What would need to be true for us to revisit this in six months?\" That one sentence converts a dead end into a scheduled conversation with criteria attached. Get the criteria named, get the date on a calendar, and hit the criteria loudly. A no with a date is a slow yes; a no you absorb silently is just a no." },
        { kind: "callout", title: "The rule", text: "Whatever gets agreed exists only in writing. Managers change jobs, recruiters forget, and a verbal promise binds nobody a year later. The same day you shake on anything, send the email: \"Thanks for the call. Confirming what we agreed: $66,000 base, $3,000 signing bonus, and a compensation review six months from my start date with a raise to $71,000 if I meet the goals we set.\" Three minutes, and it reads as competence, never as distrust." },
        { kind: "example", title: "Worked example: the recovery", text: "Back to Maya and her blurted $58,000. Two weeks after the phone screen, the offer arrives: $60,000, and the recruiter notes, kindly, that it is above what she asked for. It feels like a win and it is a trap; her nervous guess has become the yardstick. That night she finally does the research she skipped. Postings for her exact title in range-disclosure states show $64,000 to $79,000. Levels.fyi and Payscale cluster near $70,000. A former teammate one level up tells her $72,000 would not raise an eyebrow. She asks for two days, then calls back: \"I'm genuinely excited about this. Since we first spoke I've gotten a much clearer picture of the role's scope, and looking at the market, I was expecting something closer to $72,000.\" Then she stops talking. Nine seconds. The recruiter will check with the team. Next day: $66,000, base capped for this cycle. Maya moves down the levers: \"If $66,000 is the ceiling right now, could we do a $3,000 signing bonus, and a six month review with a path to $71,000?\" They land exactly there, criteria included, and she confirms every number by email that afternoon. The early blurt cost her something real. The recovery got most of it back: $6,000 more base than the offer, $3,000 in cash, a dated path to $71,000, and every future percentage now compounding on 66 instead of 60." },
        { kind: "steps", title: "The Whole Arc", steps: [
          { label: "Research the range", text: "Posted listings, aggregate sites in chorus, and one human a step ahead of you. Leave with a floor, a target and three data points you can say out loud." },
          { label: "Make them go first", text: "Answer the expectations question with a question about the budgeted range. If a form demands digits, type the top of your researched range." },
          { label: "Counter once, then silence", text: "Enthusiasm, your number, one strong reason. Then stop talking and count the seconds. Someone else speaks first." },
          { label: "Move the other levers", text: "When base stalls: signing bonus, start date, remote days, title, and an early review with a defined raise attached." },
          { label: "Get it in writing", text: "A same day email confirming every number and every date. Anything unwritten does not exist." },
        ] },
        { kind: "p", text: "Maya's whole recovery took one evening and two phone calls, and the discomfort peaked at nine seconds. The difference lands in every paycheck from now on, and in every percentage ever taken on those paychecks, at this job and the next one, because the next offer will be benchmarked against this one. That is the trade: minutes of rehearsed awkwardness against years of compounding." },
      ],
      takeaways: [
        "Whoever names the first number sets the anchor the whole negotiation orbits, so make the first number the company's range, not your guess.",
        "The person across the table works inside a band they did not set and are not paying from their own pocket, which makes your counter routine, not rude.",
        "A $5,000 difference at 23 rides every percentage raise afterward; the illustrative version runs past $100,000 by 40 with no promotions involved.",
        "Answer the expectations question with a question: ask what range has been budgeted for the role, and hold twice before ever naming a figure.",
        "When a form demands a number, type the top of your researched range, because a form can only anchor you down.",
        "After you name your number, the silence is the negotiation; whoever fills it first pays for it.",
        "A fresh offer is your lifetime leverage peak with that employer; a raise is a written case built from results, replacement cost and timing.",
        "Signing bonus, start date, remote days, title and review timing usually move more easily than base, because they live outside the band.",
        "A polite, researched counter essentially never gets an offer pulled, and nothing you agreed exists until a same day email says so.",
      ],
      theLesson: "Make the company name the first number, counter once with research behind it, let the silence sit, move to the other levers when base stalls, and confirm everything in writing the same day.",
      quiz: [
        {
          q: "Four minutes into a first phone screen, the recruiter asks for your salary expectations. Why is naming a number now so costly?",
          options: [
            "The recruiter logs it and HR treats it as your formal ask",
            "It signals you care more about the money than the role",
            "It becomes the anchor that drags every later number toward it",
            "Numbers named early get shared with other teams interviewing you",
          ],
          answer: 2,
          explain: "The mechanism is anchoring: the first number on the table sets the orbit for every number after it, which is why the side holding the band wants you to go first. Nothing gets \"shared with other teams\", and a researched number never signals caring \"more about the money\". Naming one early simply hands over the ceiling before you know where theirs was.",
        },
        {
          q: "An application form will not submit without a salary number. Best move?",
          options: [
            "Enter the top of your researched range; forms only anchor down",
            "Enter your current salary so the number is honest and checkable",
            "Enter $1 so everyone can see you consider the field meaningless",
            "Enter the bottom of your range so no filter screens you out",
          ],
          answer: 0,
          explain: "The form is a filter, not a contract, and it hurts you in only one direction: a low number anchors the conversation down, while a high one can be walked back gracefully in person. \"$1\" risks being read as a glitch or auto rejected by the software, and your current salary is exactly the anchor you are trying not to set.",
        },
        {
          q: "Why is negotiating a fresh offer different from asking for a raise a year in?",
          options: [
            "Raises are decided by HR alone, so your manager has no say in them",
            "An offer is the one moment their cost of losing you is at its peak",
            "Companies expect counters on offers but read raise requests as disloyal",
            "Offers draw on a hiring budget that raises are never allowed to touch",
          ],
          answer: 1,
          explain: "At offer time the company has spent weeks and real money choosing you, and the alternative to a small yes is restarting the search, so your leverage peaks. A raise runs on different fuel: documented results, replacement cost and timing, written as a case your manager can carry upstairs. Managers usually do have a say, and no healthy company reads a raise request as \"disloyal\".",
        },
        {
          q: "You named $72,000 and the line has been quiet for five seconds. What is happening, and what do you do?",
          options: [
            "They are offended; soften it by saying the original offer works too",
            "They expect a justification, so restate your strongest reason again",
            "The call likely dropped; check the connection and repeat the number",
            "They are checking the band and thinking; your job is to stay quiet",
          ],
          answer: 3,
          explain: "The pause is the other side doing arithmetic against a band you cannot see. Every extra word is a bid against yourself: \"the original offer works too\" donates money in one sentence, and restating your reason tells them the number is soft. You made a defensible ask. Let it sit until someone else speaks.",
        },
        {
          q: "The recruiter says the base is capped this cycle, and you believe her. The strongest next line is:",
          options: [
            "\"Could we look at a signing bonus, or an early review with a defined raise?\"",
            "\"I'll accept the base for now and reopen the number once I have started.\"",
            "\"Could you ask the hiring manager upstairs to make a one time exception?\"",
            "\"I'd want to see that cap in writing before this conversation continues.\"",
          ],
          answer: 0,
          explain: "One-time money and future money usually live outside the band, which makes a signing bonus or a scheduled review with a named number an easier yes than base. Planning to \"reopen the number once I have started\" throws away your leverage peak, and demanding the cap \"in writing\" treats a probable truth as an insult.",
        },
        {
          q: "You and the manager verbally agree: $66,000 base, a $3,000 signing bonus, a review in six months. What still has to happen today?",
          options: [
            "Nothing; a verbal agreement with a manager binds the whole company",
            "A same day email confirming every number and date you both agreed to",
            "A call to HR asking them to witness and file the verbal agreement",
            "A thank you note only, since restating the details can read as distrust",
          ],
          answer: 1,
          explain: "Anything not in the offer letter or a confirming email does not exist: managers change jobs and memories fade. The email takes three minutes and reads as competence, not \"distrust\". HR does not \"witness\" phone calls, and a verbal promise binds nobody a year later when the person who made it is gone.",
        },
      ],
      cards: [
        { front: "The anchor rule", back: "The first number named drags every later number toward it, even when everyone knows it was a guess. Never go first." },
        { front: "Dodging the expectations question", back: "\"I'd rather make sure the role is a fit before we get into numbers. Can you share the range budgeted for the position?\" Hold once more if pressed." },
        { front: "When a form demands a number", back: "Type the top of your researched range. A form is a filter, not a contract, and it can only anchor you down." },
        { front: "Research worth trusting", back: "Posted ranges in disclosure states, aggregate sites read in chorus, and one person a step ahead asked \"would $X be out of line?\" Leave with a floor, a target and three data points." },
        { front: "The counter, in four beats", back: "Enthusiasm, then \"I was expecting something closer to [your number]\", then one strong reason, then silence." },
        { front: "What the silence is for", back: "The other side is checking the band and deciding what to take upstairs. Every word you add is a bid against yourself." },
        { front: "Offer versus raise", back: "An offer is your leverage peak: they chose you and restarting the search is expensive. A raise is a one page case built from results, replacement cost and timing." },
        { front: "The movable levers", back: "Start date, signing bonus, remote days, review timing and title usually move more easily than base, because one-time and future money live outside the band." },
        { front: "Nothing exists unwritten", back: "Confirm every agreed number and date in a same day email. Verbal promises leave the building when the manager does." },
      ],
      action: "Tonight, pull the range for your job title, or the one you want next, from three sources: posted listings in a state that requires ranges, one aggregate site, and one person if you can reach them. Write down your floor and your target, then say the deflection line and the counter line out loud twice each, with your real number in them.",
    },
    "index-funds-explained": {
      hook: "One purchase makes you part owner of a few thousand companies, and a fee that looks like nothing decides six figures of the ending.",
      blocks: [
        { kind: "p", text: "Thursday, 11:20 p.m. You opened the brokerage account nineteen days ago, which took nine minutes and felt like a rite of passage. You even moved $600 into it. And there the $600 sits, in something called a cash sweep, earning close to nothing, because every time you tap Buy the screen asks for a ticker symbol and you do not have one. Last week you typed in the name of a company you like, saw that one share cost more than your grocery budget, felt like a tourist, and closed the app. So the bravest financial move of your year is parked at the curb, and the reason is not laziness. Nobody ever told you what you are supposed to be buying, or what the thing even is." },
        { kind: "p", text: "This unit answers exactly that. The 13th Grade already sold you on why investing beats waiting and where it sits in the order of operations. This is the level below: what an index fund actually is, down to what you own, what it quietly costs, and what it is going to feel like to hold one through a bad year. By the end, the ticker box stops being a wall." },
        { kind: "h", text: "What A Fund Actually Is" },
        { kind: "p", text: "Start with the word fund, because it is doing more work than it looks like. A fund is a pool. Thousands of people put money in, the pool buys shares of companies, and each person owns a slice of the pool. When you buy one share of a total market fund for, say, $120, you are not buying a ticket whose price wiggles for mysterious reasons. You are buying a very thin slice of actual ownership in several thousand real companies at once. The airline, the grocery chain, the company that makes the chips in your phone, the boring one that sells industrial glue. Their buildings, their patents, their profits. You own a sliver of all of it, and you can look up the exact list." },
        { kind: "p", text: "The width is the entire point. Any single company can go to zero, and famous ones have: giants of their decade that ended as case studies. A basket of several thousand cannot go to zero unless nearly every business on the continent fails at once, at which point money is the least of anyone's problems. Owning everything trades the lottery outcome, where one pick makes you rich or broke, for the boring outcome: you get whatever the whole economy earns. Over long stretches, the whole economy has been a very good thing to own a piece of." },
        { kind: "callout", title: "The ownership test", text: "If you cannot say what you own, you do not own an investment, you own a hope. An index fund passes the test on day one: the list of companies is public, and your share is a fixed slice of exactly that list." },
        { kind: "h", text: "The List And The Tracker" },
        { kind: "p", text: "An index is just a list with a rule. The S&P 500 is a list of roughly the 500 largest US companies. A total market index is the longer list: essentially every US public company worth counting, a few thousand of them. Nobody manages an index. It is arithmetic, published for anyone to see. An index fund is a fund whose only job is to buy that list, in proportion, and hold it. The job is called tracking, and it is deliberately mindless: when a company grows onto the list it gets bought, when it shrinks off, it gets sold. No opinions anywhere in the building." },
        { kind: "p", text: "Now the money question. A fund that tracks a list needs a computer and a compliance officer. A fund that tries to beat the list needs analysts, a star manager, research trips and a marketing budget, and all of it gets billed to you through the fee. So the picker charges ten to thirty times what the tracker charges. That would be fine if picking worked. Decade after decade, though, most professionally picked funds finish behind the plain list they were trying to beat once their fees are subtracted. You are being asked to pay extra for a coin flip that is weighted against you." },
        { kind: "bars", title: "One Difference: The Fee", items: [
          { label: "Index fund at 0.05% a year", value: 604000, display: "$604,000", tone: "good" },
          { label: "Picked fund at 1.05% a year", value: 497000, display: "$497,000", tone: "warn" },
        ], caption: "The same $500 a month for 30 years, assuming 7 percent yearly market growth, a number chosen for this illustration. Same market, same deposits. The only difference is the fee." },
        { kind: "p", text: "Sit with what that graphic is saying. One percent sounded like a rounding error. It just took about $107,000 out of an account that only ever received $180,000 of your money. The mechanism: the fee is charged on your whole balance every year, so it grows as the balance grows, and every dollar it removes stops compounding for you forever. A fee is a return running in reverse. It is also the only number in investing you control completely, which is why this unit keeps pointing at it." },
        { kind: "bigfact", stat: "$107,000", caption: "What the 1 percent fee removed in the illustration above. Same market, same deposits. It was taken by a menu choice." },
        { kind: "h", text: "The Words On The Screen" },
        { kind: "p", text: "Back to the box that stopped you. A ticker is a fund's short name, three to five letters, the thing you actually type to buy it. Every fund's page also shows its expense ratio, the yearly fee as a percentage. Those two facts are most of what the screen was asking for. For a broad index fund, a fair expense ratio is a rounding error: the big providers charge a few hundredths of a percent. Anything near 1 percent on an index fund is a souvenir shop price, and you should walk out." },
        { kind: "table", title: "The Four Funds People Actually Buy", head: ["Fund type", "What you own", "Why pick it", "Cost check"], rows: [
          ["Total market", "Every US public company", "One fund, whole economy", "Hundredths of a percent"],
          ["S&P 500", "About 500 biggest US firms", "Nearly the same ride", "Hundredths of a percent"],
          ["International", "Companies outside the US", "The rest of the world", "Tenths of a percent"],
          ["Target date", "A mix that ages with you", "One decision, done", "A little more, still small"],
        ], caption: "Any of these, held for decades at a low fee, is a good answer. The differences among them are small next to the difference between buying one and buying none." },
        { kind: "p", text: "You will also see the same list sold in two wrappers. A mutual fund prices once a day after the market closes; an ETF trades all day like a stock. People write entire arguments about the difference. For someone buying monthly and holding for decades, it barely matters: same companies, same fee logic, same outcome. Buy whichever wrapper your account offers cheaply and without commissions, and spend the saved attention elsewhere." },
        { kind: "p", text: "And if even four choices feels like three too many, the target date fund exists for you. Pick the one with a year near your planned retirement, and it holds stocks and bonds in a mix that automatically gets more careful as that year approaches. One decision instead of four, made once. Plenty of people who understand every word of this unit still choose it, because the best plan is the one that needs nothing from you in a bad month." },
        { kind: "divider" },
        { kind: "h", text: "The Sophistication Trap" },
        { kind: "p", text: "Here is the trap, and it catches smart people specifically. Index funds are simple, so the mind files them under beginner and assumes the real investors have moved on to something with more buttons: picking stocks, timing the market, options, whatever a coworker got loud about at lunch. The filing is backwards. The people with the terminals and the research staffs are the ones who mostly fail to beat the list. Simple is the finished version of investing, and complexity is usually a fee dressed up as intelligence." },
        { kind: "quote", text: "I spent two years hunting for something smarter than the boring fund. The boring fund was the smart thing the whole time. It was just wearing normal clothes.", who: "Danielle, 14th Grade" },
        { kind: "h", text: "What A Crash Feels Like" },
        { kind: "p", text: "Now the part almost nobody tells you in advance, which is exactly why it needs saying in advance. At some point while you own this fund, its value will fall hard. Twenty percent, thirty, maybe more. Your $10,000 will read $6,800 on a Tuesday morning. Headlines will explain, persuasively, why this time is different. A relative will say they told you so. Selling will feel less like panic and more like responsibility. Every crash in history has felt like this from the inside, and the feeling is not evidence." },
        { kind: "timeline", title: "The Worst Crash In 80 Years", points: [
          { at: "Oct 2007", label: "US market at its peak" },
          { at: "Mar 2009", label: "Down more than half", note: "Seventeen months of falling", tone: "warn" },
          { at: "Mar 2013", label: "Back at the old peak", tone: "good" },
          { at: "Late 2019", label: "About double the old peak", tone: "good" },
        ], caption: "The 2008 financial crisis in four stamps. The sellers of March 2009 locked in the bottom. The people whose automatic monthly buys kept running spent that stretch buying at half price." },
        { kind: "p", text: "The long horizon is an entry requirement, and here is what it means in practice. Money you will need within about five years, for rent or a wedding or a move, does not belong in this fund, because five years is not always long enough to promise you will not be selling inside a crater. Money for a retirement that is decades away can sit through a 2008 and come out the other side, but only if its owner does. Which brings up the quieter trap: the app." },
        { kind: "callout", title: "Watch out", text: "A fund you check twice a year is an investment. The same fund checked daily becomes a slot machine that mostly shows losses, because markets fall on nearly half of all days. Daily checking is how a good instrument becomes a bad experience, and then a sale at the worst moment. Automate the buying, then close the app like it is a crockpot." },
        { kind: "example", title: "Worked example", text: "Priya, 24, a dental assistant in Mesa, opens a Roth IRA in January with $2,000 she spent a year saving. Feeling accomplished, she closes the laptop. The $2,000 sits in the settlement fund, which is cash, for three months, until a friend asks what fund she bought and she realizes the answer is none. Stumble one, fixed in ten minutes: she buys a total market index fund with a 0.04 percent expense ratio and sets an automatic $150 a month. Fourteen months later her $4,100 balance meets a real crash and reads $3,250. She starts checking every morning before work. On the worst of those mornings she sells everything, and the relief lasts about a week. Six months later the market has climbed past her selling price, and getting back in costs her roughly $450 more than staying put would have. Tuition on the lesson. She rebuys anyway, then writes two rules on a sticky note: the buys run automatically, and the app gets opened on the first Saturday of January and July, twice a year, period. The next crash costs her nothing but a bad mood." },
        { kind: "h", text: "Actually Buying One" },
        { kind: "steps", title: "First Purchase, Start To Finish", steps: [
          { label: "Pick The Account", text: "The 401(k) at work if there is a match, otherwise a Roth IRA at any major low-cost brokerage. Opening one takes about ten minutes and a driver's license." },
          { label: "Move Money In", text: "Transfer from checking, and know that it lands as cash, not invested yet. This is the step where money famously goes to sleep for years." },
          { label: "Buy The Fund", text: "Find one broad index fund: total market, S&P 500, or a target date. Confirm the expense ratio is a fraction of a percent, type the ticker, buy." },
          { label: "Automate And Leave", text: "Set an automatic monthly buy sized to your budget, then stop looking. The plan runs whether you watch it or not, and it runs better when you do not." },
        ] },
        { kind: "list", title: "The only levers you actually hold", items: [
          "How much you put in each month, which matters more than any fund choice in the first decade.",
          "What you pay in fees, the one number in investing you control to the decimal.",
          "How long you leave it alone, because time in the market is what compounding is made of.",
          "Whether you sell in a crash, the single decision that separates quiet fortunes from stories about how investing does not work.",
          "Which list you buy: a broad one at a small fee, chosen once and left alone.",
        ] },
        { kind: "p", text: "Nineteen days is long enough. The $600 already made the hard trip out of your checking account. Tonight it gets a ticker." },
      ],
      takeaways: [
        "An index fund makes you a part owner of every company on a public list, so one purchase buys a slice of nearly the whole economy.",
        "Diversification is the whole point: any single company can go to zero, but a basket of thousands cannot without the economy going with it.",
        "An index is a list with a rule, and tracking it is mindless arithmetic, which is why an index fund can charge almost nothing.",
        "Most professionally picked funds finish behind the plain list they try to beat once their fees are subtracted.",
        "In this unit's illustration, a 1 percent fee on $500 a month for 30 years cost about $107,000, more than half of every dollar deposited.",
        "Mutual fund versus ETF is packaging: for a monthly buyer holding for decades, the cheap broad fund your account offers is the right answer.",
        "A target date fund turns four decisions into one and gets more careful on its own as the year on its label approaches.",
        "A fall of 30 percent or more will happen while you own this, and the plan is written in advance: keep buying, stop watching, sell nothing.",
        "Money you need within about five years does not belong in an index fund, because five years cannot promise you will not be selling inside a crater.",
      ],
      theLesson: "An index fund is cheap part ownership of nearly everything, and the fee you pick plus the crash you sit through decide more of the outcome than cleverness ever will.",
      quiz: [
        {
          q: "You buy one share of a total market index fund. What do you actually own?",
          options: [
            "A loan to the fund company that it repays with interest",
            "A thin slice of ownership in a few thousand companies",
            "A ticket whose price the fund sets from public demand",
            "Shares in whichever company tops the list that month",
          ],
          answer: 1,
          explain: "A fund is a pool: your money joins everyone else's, the pool holds the whole list, and your share is a fixed sliver of all of it. \"A loan to the fund company\" describes a bond, not a fund share, and the difference matters because ownership, not lending, is where decades of growth come from.",
        },
        {
          q: "Why can an index fund charge a small fraction of what an actively picked fund charges?",
          options: [
            "It holds fewer companies, so there is less work to bill",
            "Regulators cap what a fund tracking an index may charge",
            "It earns its keep on trading commissions instead of fees",
            "Nobody is paid to pick: it just buys the published list",
          ],
          answer: 3,
          explain: "Tracking is arithmetic: buy the list, hold the list. Picking requires analysts, a manager and marketing, all billed to you through the fee. \"Holds fewer companies\" has it backwards, since the index fund usually holds far more companies than the picked fund does, and no regulator sets these prices.",
        },
        {
          q: "In the unit's illustration, $500 a month for 30 years at an assumed 7 percent growth, what did the extra 1 percent fee cost?",
          options: [
            "About $107,000, more than half of all the deposits made",
            "About $1,800, which is the fee applied to a typical year",
            "Almost nothing, because both funds rode the same market",
            "About $107 per year, one percent of the yearly deposits",
          ],
          answer: 0,
          explain: "The fee is charged on the entire balance every year, and every dollar it removes stops compounding forever, so a small percentage becomes six figures across decades. \"Both funds rode the same market\" is the tempting one: they did, and the fee alone still opened a six-figure gap.",
        },
        {
          q: "For someone buying monthly and holding for decades, the mutual fund versus ETF question is...",
          options: [
            "A major choice, since ETFs are built for serious investors",
            "Decided by taxes: one wrapper works only inside an IRA",
            "Mostly packaging: same list, same fee logic, same result",
            "About safety, because a mutual fund is insured like a bank",
          ],
          answer: 2,
          explain: "The wrappers differ in when they trade during the day, which matters to day traders and barely at all to a decades-long holder. \"Insured like a bank\" is false for both: investments can fall, and no wrapper changes that. Buy whichever one your account sells cheaply.",
        },
        {
          q: "A coworker says index funds are fine for beginners, but real investors pick stocks. The unit's answer?",
          options: [
            "He is right once your balance grows large enough to matter",
            "Most paid professionals lose to the plain list after fees",
            "Picking works, but only with a licensed advisor's research",
            "Both approaches even out, so it comes down to preference",
          ],
          answer: 1,
          explain: "The people with research staffs and terminals mostly finish behind the plain index once their fees are counted, so simple is the finished version, not the training wheels. \"Once your balance grows large enough\" flatters the trap: a bigger balance only makes the extra fee cost more.",
        },
        {
          q: "Your fund falls 30 percent in a bad year. What does the long horizon ask of you?",
          options: [
            "Sell now and buy back in once the recovery is confirmed",
            "Switch to a picked fund, since trackers fall with the list",
            "Pause the automatic buys until the headlines calm down",
            "Keep the automatic buys running and stop checking daily",
          ],
          answer: 3,
          explain: "Crashes are in the contract, and automatic buys during one are purchases at a discount. \"Once the recovery is confirmed\" is how people sell low and rebuy high, because recoveries get confirmed only after the cheap prices are gone. Money needed within five years should not have been here at all.",
        },
      ],
      cards: [
        { front: "Index fund", back: "A fund whose only job is to buy every company on a published list, in proportion, and hold it. You own a thin slice of all of them at once." },
        { front: "Expense ratio", back: "The yearly fee a fund charges, taken as a percentage of your whole balance. Hundredths of a percent is fair for a broad index fund; near 1 percent is a six-figure lifetime leak." },
        { front: "Ticker", back: "A fund's short trading name, three to five letters. It is the thing you actually type into the buy screen." },
        { front: "Total market vs S&P 500", back: "The whole US list of a few thousand companies versus roughly the 500 largest. Both are broad, both are cheap, and over decades they behave nearly the same." },
        { front: "Mutual fund vs ETF", back: "Two wrappers around the same list. A mutual fund prices once a day, an ETF trades all day. For a monthly buyer holding for decades, the difference barely matters." },
        { front: "Target date fund", back: "One fund holding a stock and bond mix that automatically gets more careful as your chosen retirement year approaches. One decision instead of four." },
        { front: "Why fees decide", back: "The fee is charged on the whole balance every year, and every dollar it takes stops compounding forever. It is the one investing number you fully control." },
        { front: "The sophistication trap", back: "Simple looks like the beginner move, so people pay extra for complexity. Most professional pickers finish behind the plain list after fees. Simple is the finished version." },
        { front: "What a crash asks", back: "Expect a fall of 30 percent or more at some point. Keep the automatic buys running, stop checking daily, and never hold money here that you need within about five years." },
      ],
      action: "Tonight, open your 401(k) fund menu or the site of any major brokerage and find one broad index fund. Write down three things on paper: its ticker, its expense ratio, and the expense ratio of the most expensive fund on the same page. That comparison is this whole unit in your own handwriting.",
    },
    "scam-proof": {
      hook: "The list of scams changes every year. The shape never does, and once you can name its four parts you can spot cons that have not been invented yet.",
      blocks: [
        { kind: "p", text: "It is 4:52 on a Thursday and you are carrying groceries up the stairs when your phone rings. The woman says she is with your bank's fraud department, and she is calm the way people are calm when they do this all day. Someone in Ohio is trying to put $900 on your card at a Best Buy. Did you authorize that? You did not. She reads you the last four digits of your card, which match, and says she can block it, but the account has to be secured in the next few minutes, and she will stay on the line while you do it." },
        { kind: "p", text: "Nothing about you is failing in this moment. You are not greedy and you are not slow. You are on a staircase with a bag in each hand, half your mind on dinner, being handled by someone who runs this exact script forty times a day. That is the entire trick, and it is why this unit is not a list of current scams. Lists go stale in a year. This is about the shape underneath, which has not changed in decades." },
        { kind: "h", text: "Not a Gullibility Problem" },
        { kind: "p", text: "The most dangerous belief about scams is that they work on gullible people, because everyone who holds that belief files themselves under safe. Fraud does not select for low intelligence. It selects for timing. The winning message is the one that lands while you are busy, tired, broke, lonely, or already waiting for something: a package, a job offer, a refund, a text back. Young adults are targeted constantly and lose money constantly, partly because so much of your life already arrives by text and DM that one more official-sounding message does not stand out." },
        { kind: "callout", title: "Real talk", text: "If your reaction so far is that you would never fall for any of this, you are the easiest person on this page to scam. The people who lose the most are the ones who were sure it could not be them, because certainty is exactly what keeps a person from building the habit that catches it. Confidence is not a defense. A habit is." },
        { kind: "h", text: "The Shape Never Changes" },
        { kind: "p", text: "Every scam ever run is built from some mix of four levers. Not most scams. Every scam, from a fake parking ticket text to a six-month investment con. New ones appear every season, and each one is the same four parts wearing a new coat." },
        { kind: "steps", title: "The Anatomy of a Scam", steps: [
          { label: "Authority", text: "It arrives wearing a uniform: the bank, the IRS, a sheriff, a landlord, an employer, a delivery company. Something you already answer to, so your guard is down before the ask arrives." },
          { label: "Urgency", text: "Then comes a clock. The account closes tonight, the warrant goes out at 5, another applicant wants the apartment. The deadline exists to make you decide before you can think." },
          { label: "Isolation", text: "Stay on the line. Keep this confidential. Do not trust the teller at the branch. Anyone you might talk to would say the word scam out loud, so the script keeps you away from everyone." },
          { label: "Irreversible money", text: "Finally the ask: gift cards, a wire, crypto, a cash app payment to a stranger. Always money that cannot be pulled back, because the whole plan fails if you can undo it Monday morning." },
        ] },
        { kind: "p", text: "Name any two of those in one message and treat it as a scam until proven otherwise. All four together is not a red flag, it is a signed confession. You cannot memorize next year's scams, but next year's scams will still need a uniform, a clock, a closed door, and money that cannot come back." },
        { kind: "split", title: "The Fraud Call, Translated", leftLabel: "What the message says", rightLabel: "What is actually happening", rows: [
          { left: "This is your bank's fraud department", right: "Anyone can say a name, and caller ID can be faked with cheap software" },
          { left: "Your money is in danger right now", right: "Your money is fine where it sits; the only danger on the line is the caller" },
          { left: "Move it to a safe account we opened", right: "Banks never do this; the safe account belongs to the scammer" },
          { left: "Keep this confidential while we work", right: "Isolation, so nobody near you can say the word scam out loud" },
          { left: "This has to be resolved in 30 minutes", right: "A clock, so you decide before the thinking part of you shows up" },
        ] },
        { kind: "h", text: "Follow the Money" },
        { kind: "p", text: "If you keep only one tell from this unit, keep the payment method, because it is the one part of the con the scammer cannot disguise. The story can be anything. The money has to actually move, and it has to move in a way you cannot undo once the fog clears. That constraint is why the ask is always drawn from the same short list." },
        { kind: "table", title: "Can the Money Come Back?", head: ["Method", "Reversible?", "Who actually asks for it"], rows: [
          ["Gift cards", "Never", "No one legitimate, ever"],
          ["Wire transfer", "Almost never", "Closings you set up yourself"],
          ["Crypto", "Never", "Exchanges you went looking for"],
          ["Cash apps", "Rarely", "People you know in person"],
          ["Credit card", "Yes, by dispute", "Ordinary businesses"],
        ], caption: "Reversibility is the whole game. Scammers order from the top of this table; the bottom row is the safest way to pay anyone you do not know." },
        { kind: "callout", title: "The rule", text: "No legitimate company, bank, or government agency has ever required payment by gift card, wire transfer, crypto, or cash app. Not for taxes, not for fees, not to secure an account, not once in history. The moment anyone asks for one of these, the conversation is over. This single rule, followed without exception, stops most scams by itself." },
        { kind: "h", text: "The Ones You Will Meet" },
        { kind: "p", text: "The four levers are the spine. Here are the coats they wear right now. Read the list once so the first contact feels familiar instead of new." },
        { kind: "list", title: "Six to recognize on sight", items: [
          "The job that pays first: a remote offer sends you a check for equipment and asks you to forward part of it to a vendor. The check is fake and bounces after your real money is gone.",
          "The apartment you cannot see: a great listing, an out-of-town landlord, and a deposit required to hold it before any viewing. There is no apartment, or it belongs to someone else.",
          "The safe account: a caller from your bank says your money is in danger and walks you through moving it somewhere protected. The destination is theirs.",
          "The slow romance: months of daily conversation with someone you never meet, then a crisis, a ticket, a customs fee, or an investment tip. The relationship itself is the product.",
          "The investment that found you: a stranger, or a friend's hacked account, is making easy money in crypto and wants to show you how. Real opportunities do not do outreach.",
          "The little fee: a text about a package, an unpaid toll, or a refund, with a link and a $2 to $4 charge. The fee is bait; the prize is your card number and your login.",
        ] },
        { kind: "p", text: "Most of these are over in an afternoon. The romance and investment versions are not, and because the slow ones take the most money, they get their own map." },
        { kind: "timeline", title: "Anatomy of the Long Con", points: [
          { at: "Week 1", label: "A wrong-number text apologizes, then keeps chatting. Friendly, patient, no asks." },
          { at: "Month 1", label: "Daily conversation now. They mention their investing in passing and never push." },
          { at: "Month 2", label: "Screenshots of gains appear. They offer to walk you through one small trade." },
          { at: "Month 3", label: "You put $200 on their platform. It grows. You withdraw $150 and it actually arrives." },
          { at: "Month 4", label: "Confident now, you move real money in. $3,000, then more, maybe savings.", tone: "warn" },
          { at: "Month 5", label: "Withdrawals freeze. A tax must be paid to release your funds. Then the site is gone.", tone: "warn" },
        ], caption: "The withdrawal that works in month 3 is the most expensive part of the con. It is bait, priced in from the first text." },
        { kind: "divider" },
        { kind: "h", text: "The Callback Habit" },
        { kind: "p", text: "Verification only protects you if it is a habit, run every time without weighing whether this call feels real. The habit has three beats: hang up, look up, call back. End the contact, find the institution's number yourself, on the back of your card or inside the official app, and call that. Never the number the message gave you, never the link in the text." },
        { kind: "p", text: "Here is why it works. The scammer controls exactly one thing: the channel that reached you. Caller ID can be spoofed, an email address can be forged, a text can claim anything. A call you place to a number you already had is the one channel they cannot touch. It lands at the real bank no matter what the last ten minutes claimed, and if your account truly has a problem, the fraud team you call will see it and handle it. The 60 seconds a callback costs defeats scripts that fool doctors and engineers." },
        { kind: "callout", title: "Watch out", text: "The code texted to your phone is the key to your account, not a formality. Anyone asking you to read it out loud is logging in as you while you speak. No real company asks for it. Ever. This one goes for romantic partners of three weeks, too." },
        { kind: "example", title: "Marcus and the $2,850 Check", text: "Marcus, 21, applies to a remote assistant job on a real job board. The interview happens over chat, the offer is $23 an hour, and onboarding is fast: the company mails him a check for $2,850 to buy a laptop and software from their approved vendor. He deposits it by phone, and by the next morning his banking app shows the money as available. The vendor asks for $800 by cash app to reserve the laptop, and Marcus, looking at a balance that says the funds are there, sends it. Then the vendor asks for the remaining $1,600 in gift cards, for faster processing, and the word gift cards trips the rule. Marcus stops, calls the number on the back of his card, and asks whether the check has actually cleared. It has not. Available is a courtesy the bank extends while a check processes; it is not proof the check is real. Four days later the check bounces, the bank claws back the full $2,850, and Marcus is out the $800 he forwarded plus an overdrawn week. But because he stopped at the gift card ask instead of after it, he kept $1,600, and because he filed the same day, at reportfraud.ftc.gov and ic3.gov, his bank had everything it needed to close the dispute cleanly. The scam cost him $800. The rule saved him twice that." },
        { kind: "h", text: "The First Hour After" },
        { kind: "p", text: "If it happens anyway, and it happens to careful people, the two enemies are shame and time. Shame keeps people from telling anyone. Time is what the money needs to disappear. The windows for recalling a wire or disputing a charge are short, so the first hour matters more than the first week." },
        { kind: "steps", title: "The First Hour", steps: [
          { label: "Cut all contact", text: "Stop replying, block the number, do not answer follow-ups. Anyone who reaches out offering to recover your money is the same scam wearing a second coat." },
          { label: "Call your bank", text: "Use the number on the back of your card and ask for the fraud team. Wires can sometimes be recalled and card charges disputed, but only if you are fast." },
          { label: "Lock what they touched", text: "Change the password on any account you named, and freeze your credit with all three bureaus if you shared your Social Security number or a photo of your ID." },
          { label: "File the reports", text: "reportfraud.ftc.gov and ic3.gov each take minutes, and a police report strengthens your bank's case. Reports are also how the next person gets warned." },
          { label: "Tell one person", text: "Say it out loud to somebody today. Shame is the scam's last line of defense, and it only works while you keep the secret." },
        ] },
        { kind: "h", text: "Rules Beat Suspicion" },
        { kind: "p", text: "Here is the trap in this unit: hearing all of this and deciding the answer is to trust nothing. Constant suspicion fails, because it runs on willpower, and willpower is exactly what you do not have at 4:52 on the stairs. Worse, a person exhausted from doubting everything eventually starts waving things through. What holds is a short set of hard rules you follow without deliberating, the way you buckle a seatbelt without debating the crash statistics each morning." },
        { kind: "bigfact", stat: "4 parts", caption: "Urgency, authority, isolation, irreversible money. Every con that exists, and every one not invented yet, still needs all four." },
        { kind: "list", title: "The hard rules", items: [
          "Never pay anyone you have not met in person with gift cards, a wire, crypto, or a cash app, no matter how good the story is.",
          "Never act on a call or message you did not start. Hang up and call back on a number you already had.",
          "Never read a texted code to anyone, for any reason. The person asking for it already has your password.",
          "Never send money for a job, for an apartment you have not walked through, or for an investment brought to you by a stranger.",
          "Anyone who cannot wait 20 minutes while you check is answering your question for you.",
        ] },
        { kind: "quote", text: "I did not outsmart anybody. I hung up and called the number on my card. Under a minute, and it is still the best money decision I have ever made.", who: "Marcus, 14th Grade" },
      ],
      takeaways: [
        "Scams select for timing, not intelligence; the winning message is the one that lands while you are busy, tired, or already waiting for something.",
        "Every scam is built from four levers: urgency, authority, isolation, and a payment that cannot be reversed.",
        "Two levers in one message means scam until proven otherwise; you never need to name the specific con.",
        "Gift cards, wires, crypto, and cash app payments to strangers are the payment tell, and no legitimate institution has ever required any of them.",
        "Never act on inbound contact about money; hang up and call the number on the back of your card or in the official app, because that is the one channel a scammer cannot control.",
        "Money showing as available after a check deposit proves nothing; a fake check can bounce weeks later, after the money you forwarded is gone.",
        "A small withdrawal that works early in an investment relationship is bait, priced in to earn a much larger deposit.",
        "In the first hour after a scam, call your bank's fraud line first, then lock accounts, then file at reportfraud.ftc.gov and ic3.gov; speed limits the damage and silence protects the scammer.",
        "Constant suspicion exhausts you and fails; a short set of hard rules followed without deliberation is the defense that holds.",
      ],
      theLesson: "Every scam ever written runs on urgency, authority, isolation, and irreversible money, so a few hard rules aimed at those four beat any list of current cons.",
      quiz: [
        {
          q: "A scam message is most likely to succeed when it reaches you...",
          options: [
            "while you are bored, with plenty of time to pick it apart",
            "in the middle of something it was shaped to fit",
            "only if you have never heard of that exact scam",
            "only if you tend to trust strangers too easily",
          ],
          answer: 1,
          explain: "Fraud selects for timing, not intelligence. A fake delivery text lands hardest on someone actually waiting for a package, and a fraud call lands hardest mid-errand. Being bored with \"time to pick it apart\" is when scams fail, and having \"never heard of that exact scam\" barely matters, because every scam runs on the same four levers.",
        },
        {
          q: "Which payment request should end the conversation immediately, every time?",
          options: [
            "A credit card payment on a company's own website",
            "A recurring monthly charge to a service you signed up for",
            "Any ask for gift cards, a wire, crypto, or a cash app",
            "An invoice you are allowed to pay after the work is done",
          ],
          answer: 2,
          explain: "Those four methods are chosen because the money cannot be pulled back, and no legitimate company, bank, or agency has ever required them. \"A credit card payment\" is actually the safest way to pay a stranger, because a bad charge can be disputed and reversed.",
        },
        {
          q: "The fraud department calls and your caller ID shows your bank's real name. Why is hanging up and calling the number on your card still the right move?",
          options: [
            "Caller ID can be faked; a call you place reaches only the real bank",
            "The real fraud team answers callbacks faster than inbound holds",
            "Calling back proves to the bank that you take security seriously",
            "Callback lines are recorded, so scammers avoid ever using them",
          ],
          answer: 0,
          explain: "The scammer controls exactly one thing, the channel that reached you, and caller ID is trivial to spoof. A call you originate to a number you already had lands at the real institution no matter what the last call claimed. Answer speed and recordings have nothing to do with it; the point is who controls the channel.",
        },
        {
          q: "You deposit a new employer's $2,850 check and your app shows the money as available the next morning. What do you actually know?",
          options: [
            "The check cleared, so the money is yours to spend",
            "The bank confirmed the employer's account is real",
            "You are fully protected, because the bank accepted the deposit",
            "Very little; available is a courtesy and the check can still bounce",
          ],
          answer: 3,
          explain: "Banks release funds before a check finishes processing as a convenience, so \"available\" is not the same as cleared. A fake check can bounce one to two weeks later, and the bank claws the full amount back from you. Nothing about accepting a deposit means \"the employer's account is real\" or that you are protected.",
        },
        {
          q: "Three months into an investment chat with someone you have never met, the platform lets you withdraw $150 of gains, and it arrives. What is that withdrawal?",
          options: [
            "Proof the platform is real, since a scam would never pay out",
            "Bait, spent on you to set up a much larger deposit",
            "A sign the platform is risky but probably legitimate",
            "A red flag only if the withdrawal took several days",
          ],
          answer: 1,
          explain: "Long cons budget for small early payouts the way a casino budgets for free chips, because the $150 that arrives is what convinces you to move in $3,000. \"A scam would never pay out\" is exactly the belief the payout is built to install. Speed of the withdrawal changes nothing.",
        },
        {
          q: "You realize you wired $800 to a scammer twenty minutes ago. Your first call goes to...",
          options: [
            "the fraud line printed on the back of your bank card",
            "the police, so there is an official report on file first",
            "the scammer, to demand that they send the money back",
            "a recovery service you found that retrieves stolen funds",
          ],
          answer: 0,
          explain: "Wires can sometimes be recalled, but the window is short, so the bank comes first and the police report comes after. Calling \"the scammer, to demand\" anything tells them to move the money faster, and \"a recovery service you found\" is usually the same scam wearing a second coat, charging you to chase your own loss.",
        },
      ],
      cards: [
        { front: "The four levers", back: "Urgency, authority, isolation, and an irreversible payment. Every scam runs on some mix of them. Name any two in one message and treat it as a scam until proven otherwise." },
        { front: "The payment tell", back: "Gift cards, wires, crypto, and cash app payments to strangers are chosen because they cannot be reversed. No legitimate company or agency has ever required them. One ask ends the conversation." },
        { front: "The callback habit", back: "Hang up, look up, call back. Use the number on the back of your card or in the official app. The scammer only controls the channel that contacted you; a call you place reaches the real institution." },
        { front: "Texted codes", back: "A one-time code is the key to your account, and anyone asking you to read it aloud is logging in as you while you speak. No real company asks for it." },
        { front: "The fake check trick", back: "Funds showing as available is a courtesy, not proof a check cleared. A fake check can bounce one to two weeks later, after the money you forwarded is long gone, and the bank takes the full amount back from you." },
        { front: "The safe account", back: "Banks never call and ask you to move money to protect it. Your money is safe where it sits. The only danger on that call is the caller, and the safe account is theirs." },
        { front: "The bait withdrawal", back: "Long-con investment scams let you take out a small early gain so you will put in far more. An early withdrawal that works is part of the sales pitch, priced in from the first message." },
        { front: "The first hour", back: "Cut contact, call your bank's fraud line, lock passwords and credit, file at reportfraud.ftc.gov and ic3.gov, and tell one person. Speed limits damage; silence protects the scammer." },
        { front: "Who scams work on", back: "Busy, tired, distracted people the script was shaped to fit, not gullible ones. Believing you are too smart to be scammed is the most exploitable trait there is." },
      ],
      action: "Tonight, save your bank's real fraud number, from the back of your card, as a contact in your phone, and turn on transaction alerts in the app. Then tell one person in your family the rule out loud: any call about moving money gets a hang up and a callback on a number we already had.",
    },
  },
};
