// The 13th Grade — full lessons for the live units.
// Voice: plain English, warm, zero jargon left unexplained.

import type { Lesson } from "./lms";

export const LESSONS_13: Record<string, Lesson> = {
  "mindset-hacks": {
    hook: "The voice in your head is either your coach or your critic. Today you pick.",
    blocks: [
      { kind: "p", text: "Nobody teaches you how to talk to yourself. So most of us copy the harshest voice we grew up around — a teacher, a relative, a coach — and replay it for free, forever. That voice feels like honesty. It's actually just a habit." },
      { kind: "h", text: "The coach test" },
      { kind: "p", text: "Here's the test: if a coach spoke to a player the way you speak to yourself after a mistake, would that player get better — or quit? Good coaches are demanding and kind at the same time. \"That wasn't your best. Here's what we fix. Go again.\" That's the tone." },
      { kind: "callout", title: "Real talk", text: "Being hard on yourself is not discipline. Discipline is doing the thing again tomorrow. Self-criticism mostly just makes tomorrow harder." },
      { kind: "h", text: "Make it small enough to win" },
      { kind: "p", text: "Motivation is unreliable. Systems aren't. The trick that actually works: shrink the habit until it's almost embarrassing. Not \"study for two hours\" — \"open the notebook.\" Not \"get fit\" — \"put on the shoes.\" Once you start, continuing is easy. Starting was always the hard part." },
      { kind: "example", title: "Worked example", text: "Priya wants to learn to code. Plan A: \"two hours every night\" — dead by Thursday. Plan B: \"open the laptop and write one line after dinner.\" Most nights, one line becomes thirty minutes. Some nights it stays one line. Both count, because the streak survives." },
      { kind: "bigfact", stat: "66 days", caption: "roughly how long an average habit takes to feel automatic — not 21. Plan for the long middle, not the first week." },
      { kind: "list", title: "The starter kit", items: [
        "Pick one habit. Only one. Stacking five new habits is how you end up with zero.",
        "Attach it to something you already do — after brushing teeth, after dinner, after class.",
        "Track it somewhere you can see. A calendar and a pen beat any app.",
        "When you miss a day — and you will — the rule is: never miss twice.",
      ] },
      { kind: "p", text: "One more thing about the critic voice. You don't defeat it by arguing. You defeat it by getting so specific it has nothing to say. \"I'm bad at math\" is unanswerable. \"I got question four wrong because I rushed the second step\" is a to-do item. Specificity is self-respect." },
    ],
    quiz: [
      {
        q: "You bombed a presentation. What does the coach voice sound like?",
        options: [
          "\"You always do this. You're just not a presenter.\"",
          "\"That wasn't your best. The opening was rushed — fix that and go again.\"",
          "\"It was fine, don't think about it.\"",
          "\"Everyone else was worse, honestly.\"",
        ],
        answer: 1,
        explain: "The coach voice is demanding and kind at the same time — it names one specific fix and points you at the next attempt. Denial and comparison don't make the next one better.",
      },
      {
        q: "Why shrink a new habit until it's almost embarrassing?",
        options: [
          "Small habits impress people more",
          "It tricks your brain into thinking it's done",
          "Starting is the hard part — a tiny habit makes starting nearly free",
          "So you never have to do the full version",
        ],
        answer: 2,
        explain: "Once you've started, continuing is easy. \"Open the laptop\" removes the barrier that kills most habits: the start.",
      },
      {
        q: "You missed a day of your new habit. What's the rule?",
        options: [
          "Start the whole streak over from zero as punishment",
          "Quit — the streak is broken so the habit failed",
          "Double up tomorrow to make up for it",
          "Never miss twice",
        ],
        answer: 3,
        explain: "One missed day is noise. Two missed days is the start of a new habit — the habit of not doing it. Protect the day after a miss.",
      },
      {
        q: "What actually quiets the critic voice?",
        options: [
          "Arguing with it until you win",
          "Getting so specific about what went wrong that there's only a to-do item left",
          "Positive affirmations, repeated daily",
          "Avoiding situations where you might fail",
        ],
        answer: 1,
        explain: "\"I'm bad at math\" is a verdict. \"I rushed step two on question four\" is a fix. The critic can't argue with a to-do list.",
      },
    ],
    cards: [
      { front: "The coach test", back: "Would a player get better — or quit — if a coach talked to them the way you talk to yourself? Demanding and kind, at the same time." },
      { front: "Why tiny habits work", back: "Starting is the hard part. Shrink the habit until starting is nearly free: \"open the notebook,\" not \"study two hours.\"" },
      { front: "Habit stacking", back: "Attach the new habit to something you already do daily: after brushing teeth, after dinner, after class." },
      { front: "Never miss twice", back: "One missed day is noise. Two in a row is a new habit forming — the wrong one. Guard the day after a miss." },
      { front: "How long until a habit feels automatic?", back: "About 66 days on average — not 21. Plan for the long middle, not the first week." },
      { front: "Beating the critic voice", back: "Don't argue — get specific. Turn \"I'm bad at this\" into \"here's the exact step I got wrong.\" Specificity is self-respect." },
    ],
    action: "Pick one habit, shrink it until it's almost embarrassing, and attach it to something you already do every day. Start tonight.",
  },

  "money-101": {
    hook: "Your paycheck already has a plan. The only question is whether it's yours.",
    blocks: [
      { kind: "p", text: "Budgeting has a branding problem. It sounds like punishment — spreadsheets, guilt, no bubble tea. Real budgeting is the opposite: it's deciding what your money does before the month decides for you." },
      { kind: "h", text: "Where the paycheck actually goes" },
      { kind: "p", text: "First, the number on your offer letter is not the number that hits your account. Taxes, Social Security, Medicare, maybe insurance and retirement come out first. A $60,000 salary is roughly $3,900 a month after typical deductions, not $5,000. Knowing your real take-home is step zero of every money decision." },
      { kind: "callout", title: "Real talk", text: "If you don't know your monthly take-home number right now, that's the whole homework. Everything else in this course builds on it." },
      { kind: "h", text: "The 50/30/20 starting point" },
      { kind: "list", title: "One popular split of take-home pay", items: [
        "50% needs — rent, groceries, transport, minimum debt payments, insurance",
        "30% wants — eating out, trips, subscriptions, the fun stuff (on purpose, guilt-free)",
        "20% future you — savings, extra debt payments, investing",
      ] },
      { kind: "p", text: "It's a starting point, not a law. In an expensive city, needs might eat 65% and that's reality, not failure. The point is that every dollar has a job you assigned. \"Wants\" being a category means fun is planned, not leaked." },
      { kind: "example", title: "Worked example", text: "Arjun takes home $3,800 a month. Needs: $1,950 (rent $1,400, groceries $250, phone + transit + insurance $300). Future: $760 on autopilot — $400 to savings, $360 to his 401(k). Wants: whatever's left, about $1,090, spent completely guilt-free. He checks his accounts twice a month, not daily." },
      { kind: "bigfact", stat: "2 numbers", caption: "are enough to run a budget: your monthly take-home, and what your needs cost. Everything else is adjusting the leftovers." },
      { kind: "p", text: "Last thing: automate the boring parts. Savings that move themselves on payday don't require willpower. The version of you on payday is more responsible than the version of you at 11pm in a checkout screen — let payday-you make the calls." },
    ],
    quiz: [
      {
        q: "Your offer letter says $60,000. Why is your monthly budget NOT based on $5,000?",
        options: [
          "Because you should always budget lower to be safe",
          "Taxes and deductions come out first — take-home is what actually lands",
          "Employers usually pay less than the offer letter says",
          "Because rent is due before payday",
        ],
        answer: 1,
        explain: "Taxes, Social Security, Medicare, insurance, and retirement contributions come out before the money reaches you. Budget from take-home, always.",
      },
      {
        q: "In the 50/30/20 split, the 20 goes to…",
        options: [
          "Wants — you earned it",
          "Rent, because rent always comes first",
          "Future you: savings, investing, extra debt payments",
          "Emergency spending only",
        ],
        answer: 2,
        explain: "50 needs, 30 wants, 20 future. The 20% is the part that compounds — it's the reason the split exists.",
      },
      {
        q: "Your needs eat 65% of take-home because your city is expensive. What's the right read?",
        options: [
          "You're failing at budgeting and should feel bad",
          "The split is a starting point — adjust the other categories and keep every dollar assigned",
          "Move cities immediately",
          "Stop tracking, since the split doesn't fit",
        ],
        answer: 1,
        explain: "50/30/20 is a template, not a law. High-cost cities break the ratios; the principle — every dollar has a job you gave it — still holds.",
      },
      {
        q: "Why automate savings on payday?",
        options: [
          "Banks pay more interest on automated transfers",
          "It looks responsible on your credit report",
          "Payday-you makes better decisions than 11pm-checkout-you — remove willpower from the loop",
          "So you can skip checking your accounts forever",
        ],
        answer: 2,
        explain: "Money that moves itself doesn't need discipline. Set the transfer for payday and future-you is funded before the temptations start.",
      },
    ],
    cards: [
      { front: "Take-home pay", back: "What actually lands in your account after taxes, Social Security, Medicare, insurance, and retirement deductions. Budget from this, never the salary." },
      { front: "50/30/20", back: "A starting split of take-home pay: 50% needs, 30% wants, 20% future you (savings, investing, extra debt payments)." },
      { front: "\"Wants\" as a category", back: "Fun that's planned is guilt-free. Fun that leaks is a mystery charge. Same money, different feeling." },
      { front: "The two numbers that run a budget", back: "Monthly take-home, and what your needs cost. Everything else is deciding what to do with the difference." },
      { front: "Pay yourself first", back: "Automate savings to move on payday, before you can spend them. Willpower is not a strategy." },
      { front: "Checking your accounts", back: "Twice a month on schedule beats daily anxiety. You're managing a system, not watching a scoreboard." },
    ],
    action: "Find your real monthly take-home number, then set up one automatic transfer to savings on payday — even $25 counts. The habit matters more than the amount.",
  },

  "tax-season": {
    hook: "Taxes are a form, not a monster. Twenty minutes of vocabulary fixes most of the fear.",
    blocks: [
      { kind: "p", text: "Nobody explains taxes, then everyone acts like you should know them. Here's the whole game in one sentence: the government estimates your tax during the year, and in April you file a form that settles the difference — they owe you, or you owe them." },
      { kind: "h", text: "W-2 vs 1099 — the only distinction that matters early" },
      { kind: "list", items: [
        "W-2: you're an employee. Taxes come out of every paycheck automatically. Filing is usually simple.",
        "1099: you're a contractor or freelancer. Nothing was withheld — YOU owe the taxes on that money, and you may need to pay quarterly.",
        "Same money, very different paperwork. A $2,000 freelance gig is not $2,000 of spending money — set aside 25–30% of it.",
      ] },
      { kind: "callout", title: "Real talk", text: "The most common first-job mistake in this chapter: spending 1099 money like it's already been taxed. It hasn't. April will come collect." },
      { kind: "h", text: "The refund is not a gift" },
      { kind: "p", text: "A refund means you overpaid all year and the government is returning your own money, without interest. It feels like winning; it's actually a free loan you gave them. Small refund or small bill means your withholding is dialed in — that's the actual win." },
      { kind: "example", title: "Worked example", text: "Mei earns $52,000 (W-2) and made $3,000 tutoring on the side (1099). Her job withheld taxes all year, so that part settles itself. The tutoring had nothing withheld — she set aside $850 of it in a separate account in advance. At filing time she owes on the tutoring, pays it from that account, and nothing hurts." },
      { kind: "h", text: "Standard deduction — the default that's usually right" },
      { kind: "p", text: "A deduction reduces the income you're taxed on. The standard deduction is a flat amount everyone gets, no receipts needed — and for most people early in their career it beats itemizing. Free filing software will check both and pick the better one. Which brings us to:" },
      { kind: "bigfact", stat: "$0", caption: "what most people under ~$80k income should pay to file — IRS Free File and free tiers of major software exist. Paying $200 to file a W-2 return is the tax on not knowing." },
    ],
    quiz: [
      {
        q: "You made $2,000 on a freelance project (1099). What's the move?",
        options: [
          "It's $2,000 — spend it, taxes were withheld like a paycheck",
          "Set aside 25–30% — nothing was withheld, and you owe taxes on it",
          "Ignore it if it's under $5,000",
          "Wait for the client to send the taxes in for you",
        ],
        answer: 1,
        explain: "1099 income has no withholding. The taxes are your job now — park 25–30% in a separate account the day you're paid and April becomes an errand, not an emergency.",
      },
      {
        q: "A big tax refund means…",
        options: [
          "You won — free money from the government",
          "You underpaid and got lucky",
          "You overpaid all year and just got your own money back, interest-free",
          "Your employer made a mistake you should report",
        ],
        answer: 2,
        explain: "A refund is your own overpayment coming home without interest. The real win is withholding dialed in so the settle-up in April is small either way.",
      },
      {
        q: "What does the standard deduction do?",
        options: [
          "Reduces the income you're taxed on, no receipts required",
          "Delays your filing deadline",
          "Refunds your withholding automatically",
          "Only applies if you own a home",
        ],
        answer: 0,
        explain: "It's a flat amount subtracted from your taxable income — the default that beats itemizing for most people early in their career.",
      },
      {
        q: "You earn $55k at a W-2 job and have simple taxes. What should filing cost you?",
        options: [
          "Around $200 — professional help is always worth it",
          "Nothing — free filing options cover exactly this situation",
          "It depends on your refund size",
          "Filing is optional at that income",
        ],
        answer: 1,
        explain: "IRS Free File and the free tiers of major software handle a simple W-2 return at $0. Save the professional for the year your taxes actually get complicated.",
      },
    ],
    cards: [
      { front: "W-2", back: "Employee income. Taxes were withheld from every paycheck automatically — filing mostly settles the small difference." },
      { front: "1099", back: "Contractor/freelance income. Nothing withheld — you owe the taxes. Set aside 25–30% when the money arrives." },
      { front: "What filing actually is", back: "Settling the difference between what was withheld during the year and what you actually owe. They pay you, or you pay them." },
      { front: "A refund is…", back: "…your own money coming back after you overpaid all year — an interest-free loan you gave the government." },
      { front: "Standard deduction", back: "A flat amount subtracted from taxable income, no receipts needed. Usually beats itemizing early in your career." },
      { front: "Withholding", back: "The tax your employer takes out of each paycheck based on your W-4 form. Dialed-in withholding = tiny refund or tiny bill in April." },
    ],
    action: "Find last year's tax documents (or your W-4 from your current job) and check one thing: how much is being withheld per paycheck. If you have any 1099 income this year, open a separate account today and move 25–30% of it there.",
  },

  "credit-glow-up": {
    hook: "A credit score is just a trust score — and the rules of the game fit on one card.",
    blocks: [
      { kind: "p", text: "Your credit score is a number from 300 to 850 that tells lenders how reliably you repay. It decides your apartment application, your car loan rate, sometimes even a job screening. And the system never hands you a manual. Here's the manual." },
      { kind: "h", text: "What actually moves the score" },
      { kind: "list", title: "In order of weight", items: [
        "Payment history (~35%) — did you pay at least the minimum, on time, every time",
        "Utilization (~30%) — how much of your credit limit you're using; under 30% is good, under 10% is great",
        "Age of credit (~15%) — older average accounts help; this is why you keep your first card forever",
        "New credit + mix (~20%) — opening many accounts fast looks thirsty; a variety of account types mildly helps",
      ] },
      { kind: "callout", title: "Real talk", text: "One 30-days-late payment can undo a year of good behavior. If you remember one thing: autopay the minimum on everything, then pay the rest manually." },
      { kind: "h", text: "The trap the card companies are counting on" },
      { kind: "p", text: "The minimum payment is not a suggestion for how much to pay — it's the least you can pay without penalty. Carry a balance and interest (often 20%+ APR) compounds against you. The move: use the card like a debit card, pay the full statement balance every month, pay zero interest, and let the score climb anyway. You do not need to carry a balance to build credit. That's a myth that costs people thousands." },
      { kind: "example", title: "Worked example", text: "Kevin, 22, no score. He gets a secured card ($200 deposit = $200 limit), puts his Spotify and phone bill on it, autopays the full balance monthly. Utilization ~15%, payments perfect. Eighteen months later he's at 720 and qualifies for a real card with cash back — and he keeps the first card open to protect his credit age." },
      { kind: "bigfact", stat: "20%+", caption: "typical credit card APR. There is no investment that reliably beats it — which is why paying off card debt IS the best investment available to most people." },
      { kind: "p", text: "Starting from zero? Secured cards and student cards exist exactly for you. Becoming an authorized user on a parent's old, well-paid card can also jumpstart your history — a very normal family move that nobody talks about out loud." },
    ],
    quiz: [
      {
        q: "The single biggest factor in your credit score is…",
        options: [
          "Your income",
          "Paying on time, every time",
          "How many cards you have",
          "Carrying a small balance each month",
        ],
        answer: 1,
        explain: "Payment history is ~35% of the score — and income isn't a factor at all. One 30-day late mark does more damage than almost anything else.",
      },
      {
        q: "\"You need to carry a balance to build credit\" is…",
        options: [
          "True — lenders want to see interest paid",
          "True, but only in your first year",
          "A myth that costs people thousands — pay the full statement balance and the score builds anyway",
          "True only for student cards",
        ],
        answer: 2,
        explain: "The score rewards on-time payments and low utilization, not interest paid. Full statement balance every month = zero interest, same credit building.",
      },
      {
        q: "Your limit is $1,000. For a great utilization number, keep the reported balance under…",
        options: ["$900", "$500", "$300, and under $100 is even better", "It doesn't matter if you pay eventually"],
        answer: 2,
        explain: "Utilization under 30% is good, under 10% is great. High utilization signals stretched finances even if you pay in full.",
      },
      {
        q: "Why keep your first credit card open even after you get better ones?",
        options: [
          "Closing cards is illegal",
          "It protects the age of your credit history, which helps the score",
          "The bank will charge a closing fee",
          "You can't have more than one card otherwise",
        ],
        answer: 1,
        explain: "Average account age is ~15% of the score. Your oldest card is doing quiet work forever — downgrade it to a no-fee version if needed, but keep it open.",
      },
    ],
    cards: [
      { front: "Credit score", back: "A 300–850 trust score for repayment. Decides your loan rates, apartment applications, sometimes job screenings. Income is not part of it." },
      { front: "Utilization", back: "Balance ÷ credit limit. Keep under 30%; under 10% is even better. High utilization hurts even if you pay in full." },
      { front: "The minimum payment", back: "The least you can pay without penalty — not a recommendation. Carrying a balance means 20%+ APR working against you." },
      { front: "The one automation", back: "Autopay the minimum on everything (protects payment history), then manually pay the full statement balance (avoids interest)." },
      { front: "Secured card", back: "A starter card backed by your own deposit ($200 deposit = $200 limit). The standard on-ramp from \"no score\" to \"approved.\"" },
      { front: "Why keep old cards open", back: "Account age is ~15% of your score. The first card you ever opened helps you forever — just keep it at no annual fee." },
    ],
    action: "Check your credit score for free this week (your bank app almost certainly shows it). No score yet? Look up one secured or student card and read its terms — just read, no application needed.",
  },

  "invest-eventually": {
    hook: "You don't need to pick stocks. You need to buy the whole haystack and go live your life.",
    blocks: [
      { kind: "p", text: "Investing looks like a casino from the outside — tickers, candles, people yelling about coins. The boring truth: the version that works for normal people is so simple it's almost disappointing. Buy a little bit of everything, automatically, for decades." },
      { kind: "h", text: "The vocabulary, fast" },
      { kind: "list", items: [
        "Stock — a tiny slice of one company. Can go to the moon, can go to zero.",
        "Index fund — a basket holding hundreds of companies at once (an S&P 500 fund holds the 500 biggest US companies). One purchase, instant diversification.",
        "401(k) — a retirement account through your job. Money goes in before taxes, grows untaxed until retirement.",
        "Employer match — your company matches part of what you put in. This is extra salary that only exists if you claim it.",
        "Roth IRA — a retirement account you open yourself; you pay taxes now, withdrawals in retirement are tax-free.",
      ] },
      { kind: "callout", title: "Real talk", text: "If your job matches 401(k) contributions and you're not contributing to the match — you are declining part of your salary. That's the first fix, before any other investing." },
      { kind: "h", text: "Why the haystack beats the needle" },
      { kind: "p", text: "Picking winning stocks is so hard that most professional fund managers fail to beat the plain S&P 500 index over long periods. You're not going to out-research people who do this 80 hours a week — and with an index fund, you don't have to. You own all of them. The winners pull the average up for you." },
      { kind: "bigfact", stat: "~10%", caption: "average annual return of the S&P 500 over the last century, before inflation — through wars, crashes, and every headline that said this time was different." },
      { kind: "example", title: "Worked example", text: "Sana, 24, puts $200/month into an index fund and never increases it. At a historical-average return, that's roughly $400,000+ by 65 — from $98,000 of actual contributions. The gap is compounding: her early dollars spend four decades earning returns on their returns. Starting at 34 instead roughly halves the outcome. Time in the market is the whole advantage of being young." },
      { kind: "h", text: "The order of operations" },
      { kind: "list", title: "Where each dollar goes, in order", items: [
        "401(k) up to the full employer match — it's an instant 50–100% return",
        "High-interest debt (credit cards) — paying 20% APR off beats any market",
        "Emergency fund — a few months of expenses, boring account (next unit's whole story)",
        "Roth IRA, then more 401(k) — index funds inside both, on autopilot",
      ] },
      { kind: "p", text: "And when the market drops — it will, regularly — the plan is pre-written: keep buying, look away. Panic-selling in a dip is how people turn a temporary drop into a permanent loss." },
    ],
    quiz: [
      {
        q: "Your employer matches 401(k) contributions up to 4% of salary. Not contributing means…",
        options: [
          "Nothing — you'll invest later when you earn more",
          "You're declining free salary — the match is a 100% instant return",
          "You're being smart — 401(k)s lock money away",
          "You save on taxes",
        ],
        answer: 1,
        explain: "The match is compensation that only exists if you claim it. Contributing to the full match comes before every other investing move.",
      },
      {
        q: "Why do index funds beat stock-picking for normal people?",
        options: [
          "Index funds are government-insured",
          "They never lose value",
          "Most professionals fail to beat the index anyway — owning everything captures the winners without finding them",
          "Stocks are illegal to buy directly under 25",
        ],
        answer: 2,
        explain: "Even full-time professionals mostly fail to beat the S&P 500 over long periods. The index gives you the market's average, which turns out to be the winning play.",
      },
      {
        q: "You have credit card debt at 22% APR and $300 spare each month (after getting the full 401(k) match). What's the move?",
        options: [
          "Split it into index funds — never miss a month of investing",
          "Pay off the card first — a guaranteed 22% return beats the market's ~10% average",
          "Buy individual stocks to grow it faster",
          "Save it as cash until the debt clears itself",
        ],
        answer: 1,
        explain: "Paying off 22% debt is a guaranteed 22% return. No investment reliably offers that. Match first, then high-interest debt, then everything else.",
      },
      {
        q: "The market drops 20% two years into your plan. The pre-written move is…",
        options: [
          "Sell — protect what's left",
          "Stop contributing until it recovers",
          "Keep buying on schedule — you're getting the same funds at a discount",
          "Switch to picking individual winners",
        ],
        answer: 2,
        explain: "Drops are a scheduled part of the ride. Selling converts a temporary dip into a permanent loss; continuing to buy means your automatic purchases are happening on sale.",
      },
    ],
    cards: [
      { front: "Index fund", back: "One purchase that holds hundreds of companies (e.g. the S&P 500). Instant diversification; the winners pull your average up." },
      { front: "Employer 401(k) match", back: "Free additional salary that only exists if you contribute. Claiming the full match is investing move #1, always." },
      { front: "Roth IRA", back: "Retirement account you open yourself. Taxed now, tax-free in retirement — great when you're young and in a low bracket." },
      { front: "The order of operations", back: "1) 401(k) to the match → 2) kill high-interest debt → 3) emergency fund → 4) Roth IRA + more 401(k), index funds throughout." },
      { front: "Why start young", back: "Compounding needs time more than it needs money. $200/month from 24 can beat $500/month from 38." },
      { front: "When the market crashes", back: "Keep buying, look away. The plan was written for this. Panic-selling turns a temporary drop into a permanent loss." },
    ],
    action: "Log into your payroll portal and check two things: are you getting the full employer match, and what fund your money is actually in. No job benefits yet? Look up one S&P 500 index fund and note its expense ratio.",
  },

  "the-big-calls": {
    hook: "Big decisions feel heavy because you're trying to be certain. You don't need certain — you need a process.",
    blocks: [
      { kind: "p", text: "Take the job or stay? Move cities? Get serious or step back? School teaches you to find THE right answer. Life's big calls don't have one — they have trade-offs, deadlines, and incomplete information. So the skill isn't being right. It's deciding well." },
      { kind: "h", text: "Reversible vs irreversible — sort first" },
      { kind: "p", text: "Most decisions are two-way doors: you can walk through, look around, and walk back. Taking a job is more reversible than it feels — you can leave. Moving cities is reversible. A few are one-way doors: having kids, burning a relationship on the way out, certain debts. The rule: move fast through two-way doors, slow down hard for one-way doors. Most people do the opposite — agonizing over reversible calls and sleepwalking into permanent ones." },
      { kind: "callout", title: "Real talk", text: "\"What if I make the wrong choice?\" — for a reversible decision, the wrong choice costs you a detour. Staying frozen costs you the year. Indecision is also a decision, just with worse terms." },
      { kind: "h", text: "Three lenses that catch what you'd miss" },
      { kind: "list", items: [
        "10/10/10 — how will I feel about this in 10 minutes, 10 months, 10 years? Fear lives in the 10-minute view; your actual life lives in the 10-year view.",
        "The friend test — if my best friend described this exact situation, what would I tell them? You already know. You're just afraid to say it to yourself.",
        "Expected downside — what's the realistic worst case, and can I recover from it? If yes, the fear is mostly noise.",
      ] },
      { kind: "example", title: "Worked example", text: "Dev has a stable job and an offer at a smaller company — more scope, less brand name. Sort: reversible (two-way door — he can job-hunt again). 10/10/10: nervous now, likely proud in 10 months, and in 10 years the \"safe\" logo won't matter. Friend test: he'd tell a friend to go. Worst case: the startup struggles and he job-hunts in 18 months with more experience — recoverable. He goes. Not because it's guaranteed — because the process says the downside is survivable and the upside compounds." },
      { kind: "h", text: "Deciding with other people in the room" },
      { kind: "p", text: "Real calls involve parents, partners, money, and expectations. Two things help. First, separate the decision from the announcement — figure out what you actually think before you manage everyone's reactions. Second, when family pressure is part of the equation, name the real trade-off out loud: \"this path costs me X, that one costs them Y\" — it turns a guilt fog into a conversation with terms." },
      { kind: "bigfact", stat: "70%", caption: "of the information is usually enough. Waiting for 90% certainty on a reversible call mostly just means someone else got there first — or the window closed." },
    ],
    quiz: [
      {
        q: "First move on any big decision?",
        options: [
          "List every possible outcome in a spreadsheet",
          "Sort it: two-way door (reversible) or one-way door (irreversible)?",
          "Ask five people for advice",
          "Sleep on it for a month minimum",
        ],
        answer: 1,
        explain: "The sort decides the speed. Reversible calls deserve fast, decent decisions; irreversible ones deserve the slow, careful treatment. Most people reverse this.",
      },
      {
        q: "The 10/10/10 lens asks…",
        options: [
          "Ten pros, ten cons, ten alternatives",
          "How you'll feel in 10 minutes, 10 months, and 10 years",
          "Whether ten people agree with you",
          "If the decision costs more than $10, $100, or $1,000",
        ],
        answer: 1,
        explain: "Fear dominates the 10-minute view. The 10-year view is where your actual life happens — the lens exists to get you out of the short-term panic frame.",
      },
      {
        q: "Why does the friend test work?",
        options: [
          "Friends give better advice than you",
          "It removes your fear from the equation — you usually already know the answer, you're just afraid to say it to yourself",
          "It spreads responsibility if things go wrong",
          "It doesn't — never take your own advice",
        ],
        answer: 1,
        explain: "Describing your situation as someone else's strips the fear and self-image out. What's left is usually the answer you've been avoiding.",
      },
      {
        q: "You have 70% of the information on a reversible call. The move is…",
        options: [
          "Wait for 90%+ — big calls deserve full information",
          "Decide — on a two-way door, waiting for certainty usually costs more than a recoverable mistake",
          "Flip a coin, it's basically random now",
          "Hand the decision to someone with more experience",
        ],
        answer: 1,
        explain: "On reversible decisions, the cost of frozen months usually beats the cost of a correctable mistake. Certainty is for one-way doors.",
      },
    ],
    cards: [
      { front: "Two-way door", back: "A reversible decision — you can walk through and walk back. Move fast on these. Most decisions are this kind, even when they feel permanent." },
      { front: "One-way door", back: "An irreversible decision — kids, burned bridges, certain debts. These are the ones that deserve the slow, careful treatment." },
      { front: "10/10/10", back: "How will I feel in 10 minutes / 10 months / 10 years? Fear lives in the first frame; your life lives in the last one." },
      { front: "The friend test", back: "If your best friend described this exact situation, what would you tell them? You already know — say it to yourself." },
      { front: "Expected downside", back: "Define the realistic worst case and ask: can I recover? If yes, most of the remaining fear is noise." },
      { front: "70% rule", back: "On reversible calls, deciding at ~70% of the information beats waiting for certainty. Indecision has a price too — it's just quieter." },
    ],
    action: "Write down one real decision you've been circling. Sort it (two-way or one-way door), run 10/10/10 and the friend test on paper, and give yourself a decision deadline — date and time.",
  },
};
